export type ProductStatus = "validation" | "coming-soon" | "seasonal" | "quotation";

export type Product = {
  id: string;
  category: string;
  name: string;
  nameTa: string;
  description: string;
  descriptionTa: string;
  price: string;
  status: ProductStatus;
  image?: string;
  format?: string;
};

export const categories = [
  { id: "all", name: "All", nameTa: "அனைத்தும்" },
  { id: "signature", name: "Signature Brownies", nameTa: "சிக்னேச்சர் பிரௌனிகள்" },
  { id: "classics", name: "Celebration Classics", nameTa: "கொண்டாட்ட கிளாசிக்ஸ்" },
  { id: "boxes", name: "Brownie Boxes", nameTa: "பிரௌனி பெட்டிகள்" },
  { id: "tins", name: "Brownie Tins", nameTa: "பிரௌனி டின்கள்" },
  { id: "tubs", name: "Brownie Tubs", nameTa: "பிரௌனி டப்கள்" },
  { id: "tea-cakes", name: "Millet Tea Cakes", nameTa: "சிறுதானிய டீ கேக்குகள்" },
  { id: "parties", name: "Birthdays & Parties", nameTa: "பிறந்தநாள் & பார்ட்டி" },
  { id: "cupcakes", name: "Cupcakes", nameTa: "கப் கேக்குகள்" },
  { id: "gifting", name: "Personal Gifting", nameTa: "தனிப்பட்ட பரிசுகள்" },
  { id: "corporate", name: "Corporate", nameTa: "நிறுவன ஆர்டர்கள்" },
] as const;

export const menuCategories = categories.filter((category) => !["cupcakes", "parties", "corporate"].includes(category.id));

export const products: Product[] = [
  {
    id: "dark-cacao-sea-salt",
    category: "signature",
    name: "The 72 — Dark Cacao & Sea Salt",
    nameTa: "தி 72 — டார்க் காகாவ் & சீ சால்ட்",
    description: "Cacao-forward, balanced and finished with a restrained touch of sea salt.",
    descriptionTa: "அளவான கடல் உப்பு நிறைவுடன் காகாவை மையமாகக் கொண்ட பிரௌனி.",
    price: "₹927–₹1,352",
    status: "validation",
    image: "/images/brownie-closeup.png",
    format: "Egg or Eggless",
  },
  {
    id: "ragi-no-01",
    category: "signature",
    name: "Ragi No. 01 — Dark Cacao Millet Brownie",
    nameTa: "ராகி நம்பர் 01 — டார்க் காகாவ் சிறுதானிய பிரௌனி",
    description: "Dark cacao and ragi in a dense recipe with a gently roasted grain character.",
    descriptionTa: "டார்க் காகாவும் ராகியும் இணையும் அடர்த்தியான பிரௌனி.",
    price: "₹927–₹1,352",
    status: "validation",
    image: "/images/products/ragi-dark-cacao-brownie-v2.webp",
    format: "Egg or Eggless",
  },
  {
    id: "walnut-reserve",
    category: "signature",
    name: "Walnut Reserve",
    nameTa: "வால்நட் ரிசர்வ்",
    description: "Dark chocolate brownie with toasted walnut through every generous piece.",
    descriptionTa: "ஒவ்வொரு துண்டிலும் வறுத்த வால்நட்டுடன் டார்க் சாக்லேட் பிரௌனி.",
    price: "₹1,012–₹1,479",
    status: "validation",
    image: "/images/products/walnut-reserve-brownie-v2.webp",
    format: "Egg or Eggless",
  },
  {
    id: "pista-rose-cardamom",
    category: "signature",
    name: "Pista, Rose & Cardamom",
    nameTa: "பிஸ்தா, ரோஸ் & ஏலக்காய்",
    description: "Pistachio richness, warm cardamom and a restrained rose finish over dark cacao.",
    descriptionTa: "டார்க் காகாவுடன் பிஸ்தா, ரோஸ் மற்றும் ஏலக்காய் அளவாக இணையும் பிரௌனி.",
    price: "₹1,097–₹1,607",
    status: "validation",
    image: "/images/products/pista-rose-cardamom-v2.webp",
    format: "Egg or Eggless",
  },
  {
    id: "biscoff-crunch",
    category: "classics",
    name: "Biscoff Crunch Brownie",
    nameTa: "பிஸ்காஃப் கிரஞ்ச் பிரௌனி",
    description: "A limited celebration brownie with caramelised biscuit crunch.",
    descriptionTa: "கரமேலைஸ் செய்யப்பட்ட பிஸ்கட் கிரஞ்சுடன் கொண்டாட்ட பிரௌனி.",
    price: "₹1,012–₹1,479 recommended",
    status: "coming-soon",
    image: "/images/products/biscoff-crunch-v2.webp",
    format: "Ingredient verification required",
  },
  {
    id: "chocolate-wafer-crunch",
    category: "classics",
    name: "Chocolate Wafer Crunch Brownie",
    nameTa: "சாக்லேட் வேஃபர் கிரஞ்ச் பிரௌனி",
    description: "A playful chocolate-led finish with crisp wafer contrast.",
    descriptionTa: "மொறுமொறுப்பான வேஃபர் அமைப்புடன் சாக்லேட் பிரௌனி.",
    price: "₹1,012–₹1,479 recommended",
    status: "coming-soon",
    image: "/images/products/chocolate-wafer-crunch-v2.webp",
    format: "Ingredient verification required",
  },
  {
    id: "strawberry-cacao",
    category: "classics",
    name: "Seasonal Strawberry & Cacao Brownie",
    nameTa: "பருவகால ஸ்ட்ராபெரி & காகாவ் பிரௌனி",
    description: "Fresh strawberry and dark cacao, offered only when sourcing and cold-chain tests pass.",
    descriptionTa: "சோர்சிங் மற்றும் குளிர்சாதன சோதனைக்குப் பிறகு மட்டுமே கிடைக்கும் ஸ்ட்ராபெரி–காகாவ் பிரௌனி.",
    price: "₹1,097–₹1,607 recommended",
    status: "seasonal",
    image: "/images/products/seasonal-strawberry-cacao-concept-v2.webp",
    format: "Limited dates",
  },
  {
    id: "signature-discovery-box",
    category: "boxes",
    name: "Signature Discovery Box — 6 pieces",
    nameTa: "சிக்னேச்சர் டிஸ்கவரி பாக்ஸ் — 6 துண்டுகள்",
    description: "Six generous pieces as the House Six or a controlled 3+3 two-flavour composition.",
    descriptionTa: "ஹவுஸ் சிக்ஸ் அல்லது கட்டுப்படுத்தப்பட்ட 3+3 இரண்டு சுவை கலவையாக ஆறு பெரிய துண்டுகள்.",
    price: "₹927–₹1,012 recommended",
    status: "validation",
    image: "/images/products/signature-discovery-box-6-v3.webp",
    format: "Egg or Eggless · House Six or 3+3 mix",
  },
  {
    id: "reserve-collection",
    category: "boxes",
    name: "Reserve Collection — 9 pieces",
    nameTa: "ரிசர்வ் கலெக்ஷன் — 9 துண்டுகள்",
    description: "Nine generous pieces as the House Nine, a 3+3+3 mix or an expanded six-flavour assortment.",
    descriptionTa: "ஹவுஸ் நைன், 3+3+3 கலவை அல்லது ஆறு சுவைகள் கொண்ட விரிவான ஒன்பது துண்டு தொகுப்பு.",
    price: "₹1,352–₹1,607 recommended",
    status: "validation",
    image: "/images/products/reserve-collection-box-9-v3.webp",
    format: "Egg or Eggless · House Nine or mix and match",
  },
  {
    id: "brownie-tin-3-piece",
    category: "tins",
    name: "Three-Piece Brownie Tin — 1, 2 or 3 Flavours",
    nameTa: "மூன்று துண்டு பிரௌனி டின் — 1, 2 அல்லது 3 சுவைகள்",
    description: "Three separate pieces in a slim reusable Tin: 3 of one flavour, a 2+1 duo or a 1+1+1 trio from the confirmed list.",
    descriptionTa: "மெல்லிய மறுபயன்பாட்டு டினில் மூன்று தனித்தனி துண்டுகள்: ஒரே சுவையில் 3, 2+1 இரண்டு சுவைகள் அல்லது 1+1+1 மூன்று சுவைகள்.",
    price: "₹549–₹649 recommended",
    status: "validation",
    image: "/images/products/brownie-tin-3-piece-v2.webp",
    format: "3 pieces · 3+0, 2+1 or 1+1+1 composition",
  },
  {
    id: "whole-brownie-tin",
    category: "tins",
    name: "Whole Brownie Tin — 1, 2 or 3 Flavour Toppings",
    nameTa: "முழு பிரௌனி டின் — 1, 2 அல்லது 3 சுவை டாப்பிங்ஸ்",
    description: "One continuous brownie baked as a full Tin slab—not separate pieces—finished with one, two or three clearly divided flavour-topping sections.",
    descriptionTa: "தனித்தனி துண்டுகளாக அல்லாமல், டின் முழுவதும் ஒரே தொடர்ச்சியான பிரௌனி; ஒன்று, இரண்டு அல்லது மூன்று சுவை டாப்பிங் பகுதிகளுடன் முடிக்கப்படும்.",
    price: "₹549–₹649 recommended",
    status: "validation",
    image: "/images/products/brownie-tin-flight-v1.webp",
    format: "1 whole brownie slab · 1, 2 or 3 topping sections",
  },
  {
    id: "classic-brownie-tub",
    category: "tubs",
    name: "Classic Brownie Tub",
    nameTa: "கிளாசிக் பிரௌனி டப்",
    description: "Brownie pieces in a round kraft tub with a chocolate-led drizzle.",
    descriptionTa: "சாக்லேட் டிரிசிலுடன் கிராஃப்ட் பேப்பர் டப்பில் பிரௌனி துண்டுகள்.",
    price: "₹382 recommended",
    status: "coming-soon",
    image: "/images/brownie-tubs.png",
    format: "Recipe details pending",
  },
  {
    id: "loaded-brownie-tub",
    category: "tubs",
    name: "Loaded Brownie Tub",
    nameTa: "லோடெட் பிரௌனி டப்",
    description: "A celebratory tub with chocolate drizzle, walnut and declared confectionery finishes.",
    descriptionTa: "சாக்லேட் டிரிசில், வால்நட் மற்றும் அறிவிக்கப்பட்ட கான்ஃபெக்ஷனரி அலங்காரங்களுடன் டப்.",
    price: "₹467 recommended",
    status: "coming-soon",
    image: "/images/loaded-brownie-tub.png",
    format: "Allergen verification required",
  },
  {
    id: "ragi-cacao-tea-cake",
    category: "tea-cakes",
    name: "Ragi Dark Cacao Tea Cake",
    nameTa: "ராகி டார்க் காகாவ் டீ கேக்",
    description: "Ragi and dark cacao in a soft, gently structured loaf with restrained sweetness.",
    descriptionTa: "ராகி மற்றும் டார்க் காகாவுடன் அளவான இனிப்பில் மென்மையான லோஃப் கேக்.",
    price: "₹723 recommended",
    status: "coming-soon",
    image: "/images/products/ragi-dark-cacao-tea-cake-v1.webp",
    format: "Egg or Eggless after testing",
  },
  {
    id: "pista-cardamom-tea-cake",
    category: "tea-cakes",
    name: "Pista Cardamom Millet Tea Cake",
    nameTa: "பிஸ்தா ஏலக்காய் சிறுதானிய டீ கேக்",
    description: "A millet-led tea cake with pistachio richness and a measured cardamom finish.",
    descriptionTa: "பிஸ்தாவின் செறிவும் அளவான ஏலக்காய் மணமும் கொண்ட டீ கேக்.",
    price: "₹808 recommended",
    status: "coming-soon",
    image: "/images/products/pista-cardamom-millet-tea-cake-v1.webp",
    format: "Egg or Eggless after testing",
  },
  {
    id: "birthday-250",
    category: "parties",
    name: "Little Celebration — 250 g",
    nameTa: "லிட்டில் செலிப்ரேஷன் — 250 கிராம்",
    description: "A compact brownie cake for a quiet birthday or two-to-four-person celebration.",
    descriptionTa: "இரண்டு முதல் நான்கு பேர் கொண்ட சிறிய கொண்டாட்டத்திற்கான பிரௌனி கேக்.",
    price: "₹808–₹927 recommended",
    status: "validation",
    image: "/images/products/little-celebration-250g-v1.webp",
    format: "Egg or Eggless · preorder 5 days ahead",
  },
  {
    id: "birthday-500",
    category: "parties",
    name: "The Celebration — 500 g",
    nameTa: "தி செலிப்ரேஷன் — 500 கிராம்",
    description: "Our signature brownie birthday cake with a restrained finish and short message.",
    descriptionTa: "அளவான அலங்காரமும் குறுகிய வாழ்த்தும் கொண்ட பிரௌனி பிறந்தநாள் கேக்.",
    price: "₹1,488–₹1,692 recommended",
    status: "validation",
    image: "/images/birthday-cake-500g.jpg",
    format: "Egg or Eggless · preorder 5 days ahead",
  },
  {
    id: "birthday-1kg",
    category: "parties",
    name: "The Grand Celebration — 1 kg",
    nameTa: "தி கிராண்ட் செலிப்ரேஷன் — 1 கிலோ",
    description: "A generous square brownie cake for a fuller birthday gathering.",
    descriptionTa: "பெரிய கொண்டாட்டத்திற்கான சதுர பிரௌனி பிறந்தநாள் கேக்.",
    price: "₹2,678–₹3,052 recommended",
    status: "validation",
    image: "/images/birthday-cake-1kg.jpg",
    format: "Egg or Eggless · preorder 5 days ahead",
  },
  {
    id: "mini-brownie-tower",
    category: "parties",
    name: "Mini Brownie Tower",
    nameTa: "மினி பிரௌனி டவர்",
    description: "Stacked brownie pieces with a restrained drizzle and optional approved topper.",
    descriptionTa: "அளவான டிரிசில் மற்றும் விருப்பமான டாப்பருடன் அடுக்கப்படும் பிரௌனி துண்டுகள்.",
    price: "₹1,182–₹1,692 recommended",
    status: "coming-soon",
    image: "/images/mini-brownie-tower.jpg",
    format: "Pickup recommended during validation",
  },
  {
    id: "cupcake-ragi",
    category: "cupcakes",
    name: "Dark Cacao Ragi Cupcake Collection",
    nameTa: "டார்க் காகாவ் ராகி கப் கேக் தொகுப்பு",
    description: "Dark-cacao ragi cupcakes with a restrained, transport-conscious ganache finish in boxes of 6, 9 or 12.",
    descriptionTa: "போக்குவரத்துக்கு ஏற்ற அளவான கனாஷ் அலங்காரத்துடன் டார்க் காகாவ் ராகி கப் கேக்குகள்; 6, 9 அல்லது 12 பெட்டிகள்.",
    price: "₹1,097–₹2,117 planned",
    status: "coming-soon",
    image: "/images/products/cupcake-ragi-box-6-v1.webp",
    format: "Planned launch · 6, 9 or 12 · stability test pending",
  },
  {
    id: "cupcake-pista",
    category: "cupcakes",
    name: "Pista Cardamom Cupcake Collection",
    nameTa: "பிஸ்தா ஏலக்காய் கப் கேக் தொகுப்பு",
    description: "Millet cupcakes with pistachio richness and a measured cardamom finish in boxes of 6, 9 or 12.",
    descriptionTa: "பிஸ்தாவின் செறிவும் அளவான ஏலக்காய் நிறைவும் கொண்ட சிறுதானிய கப் கேக்குகள்; 6, 9 அல்லது 12 பெட்டிகள்.",
    price: "₹1,182–₹2,287 planned",
    status: "coming-soon",
    image: "/images/products/cupcake-pista-box-9-v1.webp",
    format: "Planned launch · 6, 9 or 12 · stability test pending",
  },
  {
    id: "cupcake-discovery",
    category: "cupcakes",
    name: "Cupcake Discovery Collection",
    nameTa: "கப் கேக் டிஸ்கவரி கலெக்ஷன்",
    description: "A planned mixed box across six flavour identities, configured in balanced pairs for 6, 9 or 12 cupcakes.",
    descriptionTa: "ஆறு சுவைகளில் சமநிலையான கலவையாக திட்டமிடப்பட்ட 6, 9 அல்லது 12 கப் கேக் பெட்டி.",
    price: "₹1,182–₹2,287 planned",
    status: "coming-soon",
    image: "/images/products/cupcake-discovery-box-12-v1.webp",
    format: "Planned launch · mix and match after recipe validation",
  },
  {
    id: "corporate-mini-box",
    category: "corporate",
    name: "Corporate Mini Box — 4 pieces",
    nameTa: "கார்ப்பரேட் மினி பாக்ஸ் — 4 துண்டுகள்",
    description: "A compact employee or client gift. The lead configuration is 2 Ragi + 2 Walnut Crunch, with a controlled four-flavour upgrade.",
    descriptionTa: "ஊழியர் அல்லது வாடிக்கையாளர் பரிசு. முக்கிய கலவை 2 ராகி + 2 வால்நட் கிரஞ்ச்; கட்டுப்படுத்தப்பட்ட நான்கு சுவை மேம்பாடு உண்டு.",
    price: "₹635–₹745 per box recommended",
    status: "quotation",
    image: "/images/products/corporate-mini-box-4-v3.webp",
    format: "Minimum 25 boxes · 2+2 lead composition",
  },
  {
    id: "seasonal-hamper",
    category: "gifting",
    name: "Seasonal Hamper",
    nameTa: "பருவகால ஹாம்பர்",
    description: "A limited festival composition selected around verified products and packaging.",
    descriptionTa: "சோதிக்கப்பட்ட தயாரிப்புகள் மற்றும் பேக்கிங்குடன் பருவகால பரிசுத் தொகுப்பு.",
    price: "Planning ₹1,990–₹2,990",
    status: "seasonal",
    image: "/images/products/seasonal-hamper-concept-v1.webp",
    format: "Limited edition",
  },
  {
    id: "bespoke-corporate",
    category: "corporate",
    name: "Bespoke Corporate Gifting",
    nameTa: "தனிப்பயன் நிறுவன பரிசுகள்",
    description: "Structured gifting for teams and clients, with quantity and branding controls.",
    descriptionTa: "அளவு மற்றும் பிராண்டிங் கட்டுப்பாடுகளுடன் நிறுவன பரிசுகள்.",
    price: "By quotation",
    status: "quotation",
    image: "/images/products/bespoke-corporate-gifting-v1.webp",
    format: "Minimum 25 boxes or ₹15,000",
  },
  {
    id: "party-single-brownies",
    category: "parties",
    name: "Individually Packed Party Brownies",
    nameTa: "தனித்தனியாக பேக் செய்யப்பட்ட பார்ட்டி பிரௌனிகள்",
    description: "A full-size brownie in individual food-safe presentation for birthdays, return gifts and dessert tables.",
    descriptionTa: "பிறந்தநாள், ரிட்டர்ன் கிஃப்ட் மற்றும் டெசர்ட் டேபிளுக்காக ஒவ்வொன்றும் உணவு பாதுகாப்பாக பேக் செய்யப்பட்ட முழு அளவு பிரௌனி.",
    price: "From ₹4,375 · minimum 25",
    status: "quotation",
    image: "/images/products/party-individually-packed-brownies-v1.webp",
    format: "25, 50 or 100 pieces · Egg or Eggless",
  },
  {
    id: "party-brownie-tins",
    category: "parties",
    name: "Party Brownie Tins",
    nameTa: "பார்ட்டி பிரௌனி டின்கள்",
    description: "Choose either three separate brownie pieces or one whole brownie with flavour-topping sections, supplied as reusable Tins for party favours or table placement.",
    descriptionTa: "பார்ட்டி பரிசு அல்லது டேபிள் செட்டிங்கிற்காக மூன்று தனித்தனி பிரௌனி துண்டுகள் அல்லது சுவை டாப்பிங் பகுதிகளுடன் ஒரு முழு பிரௌனி கொண்ட மறுபயன்பாட்டு டின்கள்.",
    price: "From ₹5,250 · minimum 10 Tins",
    status: "quotation",
    image: "/images/products/party-brownie-tins-v1.webp",
    format: "10 Tins · three-piece or whole-brownie format",
  },
  {
    id: "party-brownie-tubs",
    category: "parties",
    name: "Party Brownie Tubs",
    nameTa: "பார்ட்டி பிரௌனி டப்கள்",
    description: "Classic or Loaded Brownie Tubs prepared as individual party desserts with one coordinated finish.",
    descriptionTa: "ஒருங்கிணைந்த அலங்காரத்துடன் தனிப்பட்ட பார்ட்டி டெசர்ட்டாக தயாரிக்கப்படும் கிளாசிக் அல்லது லோடெட் பிரௌனி டப்கள்.",
    price: "From ₹3,750 · minimum 10 Tubs",
    status: "quotation",
    image: "/images/products/party-brownie-tubs-v1.webp",
    format: "10 Tubs · one or two approved finishes",
  },
  {
    id: "occasion-brownie-cake",
    category: "parties",
    name: "Occasion Brownie Cake",
    nameTa: "நிகழ்ச்சி பிரௌனி கேக்",
    description: "A considered brownie cake for anniversaries, engagements, welcomes, farewells and milestone occasions.",
    descriptionTa: "திருமண நாள், நிச்சயதார்த்தம், வரவேற்பு, பிரியாவிடை மற்றும் முக்கிய நிகழ்ச்சிகளுக்கான பிரௌனி கேக்.",
    price: "₹1,590–₹3,250 recommended",
    status: "quotation",
    image: "/images/products/occasion-brownie-cake-v1.webp",
    format: "500 g or 1 kg · Egg or Eggless · 5-day lead time",
  },
];

export const statusLabel: Record<ProductStatus, { en: string; ta: string }> = {
  validation: { en: "Launch validation", ta: "அறிமுக சோதனை" },
  "coming-soon": { en: "Coming soon", ta: "விரைவில் வருகிறது" },
  seasonal: { en: "Seasonal", ta: "பருவகாலம்" },
  quotation: { en: "By quotation", ta: "விலை மதிப்பீடு" },
};

export const findProduct = (id: string) => products.find((product) => product.id === id);
