export type Product = {
  id: string;
  category: string;
  name: string;
  nameTa: string;
  description: string;
  descriptionTa: string;
  image?: string;
  format?: string;
};

export const categories = [
  { id: "all", name: "All", nameTa: "அனைத்தும்" },
  { id: "signature", name: "Signature Brownies", nameTa: "சிக்னேச்சர் பிரௌனிகள்" },
  { id: "classics", name: "Celebration Classics", nameTa: "கொண்டாட்ட கிளாசிக்ஸ்" },
  { id: "boxes", name: "Brownie Boxes", nameTa: "பிரௌனி பெட்டிகள்" },
  { id: "tins", name: "Brownie Tins", nameTa: "பிரௌனி டின்கள்" },
  { id: "tubs", name: "Brownie Tubs", nameTa: "பிரௌனி டப்கள்" },
  { id: "tea-cakes", name: "Millet Tea Cakes", nameTa: "சிறுதானிய டீ கேக்குகள்" },
  { id: "parties", name: "Birthdays & Parties", nameTa: "பிறந்தநாள் & பார்ட்டி" },
  { id: "cupcakes", name: "Cupcakes", nameTa: "கப் கேக்குகள்" },
  { id: "gifting", name: "Personal Gifting", nameTa: "தனிப்பட்ட பரிசுகள்" },
  { id: "corporate", name: "Corporate", nameTa: "நிறுவன ஆர்டர்கள்" },
] as const;

export const menuCategories = categories.filter((category) => !["cupcakes", "parties", "corporate"].includes(category.id));

export const products: Product[] = [
  {
    id: "dark-cacao-sea-salt",
    category: "signature",
    name: "The 72 — Dark Cacao & Sea Salt",
    nameTa: "தி 72 — டார்க் காகாவ் & சீ சால்ட்",
    description: "Cacao-forward, balanced and finished with a restrained touch of sea salt.",
    descriptionTa: "அளவான கடல் உப்பு நிறைவுடன் காகாவை மையமாகக் கொண்ட பிரௌனி.",
    image: "/images/brownie-closeup.png",
    format: "Boxes of 6 or 9 pieces",
  },
  {
    id: "ragi-no-01",
    category: "signature",
    name: "Ragi No. 01 — Dark Cacao Millet Brownie",
    nameTa: "ராகி நம்பர் 01 — டார்க் காகாவ் சிறுதானிய பிரௌனி",
    description: "Dark cacao and ragi in a dense recipe with a gently roasted grain character.",
    descriptionTa: "டார்க் காகாவும் ராகியும் இணையும் அடர்த்தியான பிரௌனி.",
    image: "/images/products/ragi-dark-cacao-brownie-v2.webp",
    format: "Boxes of 6 or 9 pieces",
  },
  {
    id: "walnut-reserve",
    category: "signature",
    name: "Walnut Reserve",
    nameTa: "வால்நட் ரிசர்வ்",
    description: "Dark chocolate brownie with toasted walnut through every generous piece.",
    descriptionTa: "ஒவ்வொரு துண்டிலும் வறுத்த வால்நட்டுடன் டார்க் சாக்லேட் பிரௌனி.",
    image: "/images/products/walnut-reserve-brownie-v2.webp",
    format: "Boxes of 6 or 9 pieces",
  },
  {
    id: "pista-rose-cardamom",
    category: "signature",
    name: "Pista, Rose & Cardamom",
    nameTa: "பிஸ்தா, ரோஸ் & ஏலக்காய்",
    description: "Pistachio richness, warm cardamom and a restrained rose finish over dark cacao.",
    descriptionTa: "டார்க் காகாவுடன் பிஸ்தா, ரோஸ் மற்றும் ஏலக்காய் அளவாக இணையும் பிரௌனி.",
    image: "/images/products/pista-rose-cardamom-v2.webp",
    format: "Boxes of 6 or 9 pieces",
  },
  {
    id: "biscoff-crunch",
    category: "classics",
    name: "Caramelised Biscuit Crunch Brownie",
    nameTa: "கரமேலைஸ் பிஸ்கட் கிரஞ்ச் பிரௌனி",
    description: "A limited celebration brownie with caramelised biscuit crunch.",
    descriptionTa: "கரமேலைஸ் செய்யப்பட்ட பிஸ்கட் கிரஞ்சுடன் கொண்டாட்ட பிரௌனி.",
    image: "/images/products/biscoff-crunch-v2.webp",
    format: "Boxes of 6 or 9 pieces",
  },
  {
    id: "chocolate-wafer-crunch",
    category: "classics",
    name: "Chocolate Wafer Crunch Brownie",
    nameTa: "சாக்லேட் வேஃபர் கிரஞ்ச் பிரௌனி",
    description: "A playful chocolate-led finish with crisp wafer contrast.",
    descriptionTa: "மொறுமொறுப்பான வேஃபர் அமைப்புடன் சாக்லேட் பிரௌனி.",
    image: "/images/products/chocolate-wafer-crunch-v2.webp",
    format: "Boxes of 6 or 9 pieces",
  },
  {
    id: "strawberry-cacao",
    category: "classics",
    name: "Seasonal Strawberry & Cacao Brownie",
    nameTa: "பருவகால ஸ்ட்ராபெரி & காகாவ் பிரௌனி",
    description: "Fresh strawberry and dark cacao, offered on selected seasonal dates.",
    descriptionTa: "தேர்ந்தெடுக்கப்பட்ட பருவகால தேதிகளில் கிடைக்கும் ஸ்ட்ராபெரி–காகாவ் பிரௌனி.",
    image: "/images/products/seasonal-strawberry-cacao-concept-v2.webp",
    format: "Seasonal boxes of 6 or 9 pieces",
  },
  {
    id: "signature-discovery-box",
    category: "boxes",
    name: "Signature Discovery Box — 6 pieces",
    nameTa: "சிக்னேச்சர் டிஸ்கவரி பாக்ஸ் — 6 துண்டுகள்",
    description: "Six generous pieces as the House Six or a curated 3+3 two-flavour composition.",
    descriptionTa: "ஹவுஸ் சிக்ஸ் அல்லது தேர்ந்தெடுக்கப்பட்ட 3+3 இரண்டு சுவை கலவையாக ஆறு பெரிய துண்டுகள்.",
    image: "/images/products/signature-discovery-box-6-v3.webp",
    format: "House Six or a 3+3 flavour mix",
  },
  {
    id: "reserve-collection",
    category: "boxes",
    name: "Reserve Collection — 9 pieces",
    nameTa: "ரிசர்வ் கலெக்ஷன் — 9 துண்டுகள்",
    description: "Nine generous pieces as the House Nine, a 3+3+3 mix or an expanded six-flavour assortment.",
    descriptionTa: "ஹவுஸ் நைன், 3+3+3 கலவை அல்லது ஆறு சுவைகள் கொண்ட விரிவான ஒன்பது துண்டு தொகுப்பு.",
    image: "/images/products/reserve-collection-box-9-v3.webp",
    format: "House Nine or mix and match",
  },
  {
    id: "brownie-tin-3-piece",
    category: "tins",
    name: "Three-Piece Brownie Tin — 1/2/3 Flavours",
    nameTa: "மூன்று துண்டு பிரௌனி டின் — 1/2/3 சுவைகள்",
    description: "Three separate pieces in a slim reusable Tin: 3 of one flavour, a 2+1 duo or a 1+1+1 trio from the confirmed list.",
    descriptionTa: "மெல்லிய மறுபயன்பாட்டு டினில் மூன்று தனித்தனி துண்டுகள்: ஒரே சுவையில் 3, 2+1 இரண்டு சுவைகள் அல்லது 1+1+1 மூன்று சுவைகள்.",
    image: "/images/products/brownie-tin-3-piece-v2.webp",
    format: "3 pieces · 3+0, 2+1 or 1+1+1 composition",
  },
  {
    id: "whole-brownie-tin",
    category: "tins",
    name: "Whole Brownie Tin — 1/2/3 Flavour Toppings",
    nameTa: "முழு பிரௌனி டின் — 1/2/3 சுவை டாப்பிங்ஸ்",
    description: "One continuous brownie Tin with 1/2/3 clearly divided flavour-topping sections.",
    descriptionTa: "1/2/3 சுவை டாப்பிங் பகுதிகளுடன் ஒரு தொடர்ச்சியான முழு பிரௌனி டின்.",
    image: "/images/products/whole-brownie-tin-flavour-toppings-v2.webp",
    format: "1 whole brownie slab · 1/2/3 topping sections",
  },
  {
    id: "classic-brownie-tub",
    category: "tubs",
    name: "Classic Brownie Tub",
    nameTa: "கிளாசிக் பிரௌனி டப்",
    description: "Brownie pieces in a round kraft tub with a chocolate-led drizzle.",
    descriptionTa: "சாக்லேட் டிரிசிலுடன் கிராஃப்ட் பேப்பர் டப்பில் பிரௌனி துண்டுகள்.",
    image: "/images/brownie-tubs.png",
    format: "Single Tub or duo",
  },
  {
    id: "loaded-brownie-tub",
    category: "tubs",
    name: "Loaded Brownie Tub",
    nameTa: "லோடெட் பிரௌனி டப்",
    description: "A celebratory tub with chocolate drizzle, walnut and declared confectionery finishes.",
    descriptionTa: "சாக்லேட் டிரிசில், வால்நட் மற்றும் அறிவிக்கப்பட்ட கான்ஃபெக்ஷனரி அலங்காரங்களுடன் டப்.",
    image: "/images/loaded-brownie-tub.png",
    format: "Single Tub or duo · toppings vary by date",
  },
  {
    id: "ragi-cacao-tea-cake",
    category: "tea-cakes",
    name: "Ragi Dark Cacao Tea Cake",
    nameTa: "ராகி டார்க் காகாவ் டீ கேக்",
    description: "Ragi and dark cacao in a soft, gently structured loaf with restrained sweetness.",
    descriptionTa: "ராகி மற்றும் டார்க் காகாவுடன் அளவான இனிப்பில் மென்மையான லோஃப் கேக்.",
    image: "/images/products/ragi-dark-cacao-tea-cake-v1.webp",
    format: "Single loaf or gift duo",
  },
  {
    id: "pista-cardamom-tea-cake",
    category: "tea-cakes",
    name: "Pista Cardamom Millet Tea Cake",
    nameTa: "பிஸ்தா ஏலக்காய் சிறுதானிய டீ கேக்",
    description: "A millet-led tea cake with pistachio richness and a measured cardamom finish.",
    descriptionTa: "பிஸ்தாவின் செறிவும் அளவான ஏலக்காய் மணமும் கொண்ட டீ கேக்.",
    image: "/images/products/pista-cardamom-millet-tea-cake-v1.webp",
    format: "Single loaf or gift duo",
  },
  {
    id: "birthday-250",
    category: "parties",
    name: "Little Celebration — 250 g",
    nameTa: "லிட்டில் செலிப்ரேஷன் — 250 கிராம்",
    description: "A compact brownie cake for a quiet birthday or two-to-four-person celebration.",
    descriptionTa: "இரண்டு முதல் நான்கு பேர் கொண்ட சிறிய கொண்டாட்டத்திற்கான பிரௌனி கேக்.",
    image: "/images/products/little-celebration-250g-v1.webp",
    format: "Preorder at least 5 days ahead",
  },
  {
    id: "birthday-500",
    category: "parties",
    name: "The Celebration — 500 g",
    nameTa: "தி செலிப்ரேஷன் — 500 கிராம்",
    description: "Our signature brownie birthday cake with a restrained finish and short message.",
    descriptionTa: "அளவான அலங்காரமும் குறுகிய வாழ்த்தும் கொண்ட பிரௌனி பிறந்தநாள் கேக்.",
    image: "/images/birthday-cake-500g.jpg",
    format: "Preorder at least 5 days ahead",
  },
  {
    id: "birthday-1kg",
    category: "parties",
    name: "The Grand Celebration — 1 kg",
    nameTa: "தி கிராண்ட் செலிப்ரேஷன் — 1 கிலோ",
    description: "A generous square brownie cake for a fuller birthday gathering.",
    descriptionTa: "பெரிய கொண்டாட்டத்திற்கான சதுர பிரௌனி பிறந்தநாள் கேக்.",
    image: "/images/birthday-cake-1kg.jpg",
    format: "Preorder at least 5 days ahead",
  },
  {
    id: "mini-brownie-tower",
    category: "parties",
    name: "Mini Brownie Tower",
    nameTa: "மினி பிரௌனி டவர்",
    description: "Stacked brownie pieces with a restrained drizzle and optional topper.",
    descriptionTa: "அளவான டிரிசில் மற்றும் விருப்பமான டாப்பருடன் அடுக்கப்படும் பிரௌனி துண்டுகள்.",
    image: "/images/mini-brownie-tower.jpg",
    format: "Pickup preferred for this format",
  },
  {
    id: "cupcake-ragi",
    category: "cupcakes",
    name: "Dark Cacao Ragi Cupcake Collection",
    nameTa: "டார்க் காகாவ் ராகி கப் கேக் தொகுப்பு",
    description: "Dark-cacao ragi cupcakes with a restrained ganache finish, presented in larger cupcake-specific boxes with one fitted holder per cupcake.",
    descriptionTa: "அளவான கனாஷ் அலங்காரத்துடன் டார்க் காகாவ் ராகி கப் கேக்குகள்; ஒவ்வொரு கப் கேக்கிற்கும் தனி ஹோல்டர் கொண்ட பெரிய கப் கேக் பெட்டியில் வழங்கப்படும்.",
    image: "/images/products/cupcake-ragi-box-6-v2.webp",
    format: "Individual holders · boxes of 6, 9 or 12",
  },
  {
    id: "cupcake-pista",
    category: "cupcakes",
    name: "Pista Cardamom Cupcake Collection",
    nameTa: "பிஸ்தா ஏலக்காய் கப் கேக் தொகுப்பு",
    description: "Millet cupcakes with pistachio richness and a measured cardamom finish, each secured in its own holder inside a deeper cupcake box.",
    descriptionTa: "பிஸ்தாவின் செறிவும் அளவான ஏலக்காய் நிறைவும் கொண்ட சிறுதானிய கப் கேக்குகள்; ஆழமான பெட்டியில் ஒவ்வொன்றும் தனி ஹோல்டரில் பாதுகாக்கப்படும்.",
    image: "/images/products/cupcake-pista-box-9-v2.webp",
    format: "Individual holders · boxes of 6, 9 or 12",
  },
  {
    id: "cupcake-discovery",
    category: "cupcakes",
    name: "Cupcake Discovery Collection",
    nameTa: "கப் கேக் டிஸ்கவரி கலெக்ஷன்",
    description: "A mixed collection across six flavour identities, presented in a spacious cupcake box with one fitted holder per cupcake.",
    descriptionTa: "ஆறு சுவைகளில் கலவை; ஒவ்வொரு கப் கேக்கிற்கும் தனி ஹோல்டர் கொண்ட விசாலமான பெட்டியில் வழங்கப்படும்.",
    image: "/images/products/cupcake-discovery-box-12-v2.webp",
    format: "Individual holders · six-flavour mix",
  },
  {
    id: "corporate-mini-box",
    category: "corporate",
    name: "Corporate Mini Box — 4 pieces",
    nameTa: "கார்ப்பரேட் மினி பாக்ஸ் — 4 துண்டுகள்",
    description: "A compact employee or client gift with 2 Ragi + 2 Walnut pieces, or a curated four-flavour assortment.",
    descriptionTa: "2 ராகி + 2 வால்நட் துண்டுகள் அல்லது தேர்ந்தெடுக்கப்பட்ட நான்கு சுவை கலவையுடன் ஊழியர் அல்லது வாடிக்கையாளர் பரிசு.",
    image: "/images/products/corporate-mini-box-4-v3.webp",
    format: "Minimum 25 boxes · ₹12,250 before delivery",
  },
  {
    id: "seasonal-hamper",
    category: "gifting",
    name: "Seasonal Hamper",
    nameTa: "பருவகால ஹாம்பர்",
    description: "A limited festival composition presented as a considered seasonal gift.",
    descriptionTa: "கவனமாக வடிவமைக்கப்பட்ட பருவகால விழா பரிசுத் தொகுப்பு.",
    image: "/images/products/seasonal-hamper-concept-v1.webp",
    format: "Limited edition",
  },
  {
    id: "bespoke-corporate",
    category: "corporate",
    name: "Bespoke Corporate Gifting",
    nameTa: "தனிப்பயன் நிறுவன பரிசுகள்",
    description: "Structured gifting for teams and clients, with quantity and branding controls.",
    descriptionTa: "அளவு மற்றும் பிராண்டிங் கட்டுப்பாடுகளுடன் நிறுவன பரிசுகள்.",
    image: "/images/products/bespoke-corporate-gifting-v1.webp",
    format: "Starts at 25 individually packed brownies",
  },
  {
    id: "party-single-brownies",
    category: "parties",
    name: "Individually Packed Party Brownies",
    nameTa: "தனித்தனியாக பேக் செய்யப்பட்ட பார்ட்டி பிரௌனிகள்",
    description: "A full-size brownie in individual food-safe presentation for birthdays, return gifts and dessert tables.",
    descriptionTa: "பிறந்தநாள், ரிட்டர்ன் கிஃப்ட் மற்றும் டெசர்ட் டேபிளுக்காக ஒவ்வொன்றும் உணவு பாதுகாப்பாக பேக் செய்யப்பட்ட முழு அளவு பிரௌனி.",
    image: "/images/products/party-individually-packed-brownies-v1.webp",
    format: "25, 50 or 100 individually packed pieces",
  },
  {
    id: "party-brownie-tins",
    category: "parties",
    name: "Party Brownie Tins",
    nameTa: "பார்ட்டி பிரௌனி டின்கள்",
    description: "Choose either three separate brownie pieces or one whole brownie with flavour-topping sections, supplied as reusable Tins for party favours or table placement.",
    descriptionTa: "பார்ட்டி பரிசு அல்லது டேபிள் செட்டிங்கிற்காக மூன்று தனித்தனி பிரௌனி துண்டுகள் அல்லது சுவை டாப்பிங் பகுதிகளுடன் ஒரு முழு பிரௌனி கொண்ட மறுபயன்பாட்டு டின்கள்.",
    image: "/images/products/party-brownie-tins-v1.webp",
    format: "10 Tins · three-piece or whole-brownie format",
  },
  {
    id: "party-brownie-tubs",
    category: "parties",
    name: "Party Brownie Tubs",
    nameTa: "பார்ட்டி பிரௌனி டப்கள்",
    description: "Classic or Loaded Brownie Tubs prepared as individual party desserts with one coordinated finish.",
    descriptionTa: "ஒருங்கிணைந்த அலங்காரத்துடன் தனிப்பட்ட பார்ட்டி டெசர்ட்டாக தயாரிக்கப்படும் கிளாசிக் அல்லது லோடெட் பிரௌனி டப்கள்.",
    image: "/images/products/party-brownie-tubs-v1.webp",
    format: "10 Tubs · one or two coordinated finishes",
  },
  {
    id: "occasion-brownie-cake",
    category: "parties",
    name: "Occasion Brownie Cake",
    nameTa: "நிகழ்ச்சி பிரௌனி கேக்",
    description: "A considered brownie cake for anniversaries, engagements, welcomes, farewells and milestone occasions.",
    descriptionTa: "திருமண நாள், நிச்சயதார்த்தம், வரவேற்பு, பிரியாவிடை மற்றும் முக்கிய நிகழ்ச்சிகளுக்கான பிரௌனி கேக்.",
    image: "/images/products/occasion-brownie-cake-v1.webp",
    format: "500 g or 1 kg · preorder at least 5 days ahead",
  },
];

export const findProduct = (id: string) => products.find((product) => product.id === id);
