export type ProductStatus = "validation" | "coming-soon" | "seasonal" | "quotation";

export type Product = {
  id: string;
  category: string;
  name: string;
  nameTa: string;
  description: string;
  descriptionTa: string;
  price: string;
  status: ProductStatus;
  image?: string;
  format?: string;
};

export const categories = [
  { id: "all", name: "All", nameTa: "அனைத்தும்" },
  { id: "signature", name: "Signature Brownies", nameTa: "சிக்னேச்சர் பிரௌனிகள்" },
  { id: "classics", name: "Celebration Classics", nameTa: "கொண்டாட்ட கிளாசிக்ஸ்" },
  { id: "boxes", name: "Brownie Boxes", nameTa: "பிரௌனி பெட்டிகள்" },
  { id: "tins", name: "Brownie Tins", nameTa: "பிரௌனி டின்கள்" },
  { id: "tubs", name: "Brownie Tubs", nameTa: "பிரௌனி டப்கள்" },
  { id: "tea-cakes", name: "Millet Tea Cakes", nameTa: "சிறுதானிய டீ கேக்குகள்" },
  { id: "celebrations", name: "Birthday Cakes", nameTa: "பிறந்தநாள் கேக்குகள்" },
  { id: "cupcakes", name: "Cupcakes", nameTa: "கப் கேக்குகள்" },
  { id: "gifting", name: "Gifting & Corporate", nameTa: "பரிசுகள் மற்றும் நிறுவன ஆர்டர்கள்" },
] as const;

export const products: Product[] = [
  {
    id: "dark-cacao-sea-salt",
    category: "signature",
    name: "The 72 — Dark Cacao & Sea Salt",
    nameTa: "தி 72 — டார்க் காகாவ் & சீ சால்ட்",
    description: "Cacao-forward, balanced and finished with a restrained touch of sea salt.",
    descriptionTa: "அளவான கடல் உப்பு நிறைவுடன் காகாவை மையமாகக் கொண்ட பிரௌனி.",
    price: "Select a format",
    status: "validation",
    image: "/images/brownie-closeup.png",
    format: "Egg or Eggless",
  },
  {
    id: "ragi-no-01",
    category: "signature",
    name: "Ragi No. 01 — Dark Cacao Millet Brownie",
    nameTa: "ராகி நம்பர் 01 — டார்க் காகாவ் சிறுதானிய பிரௌனி",
    description: "Dark cacao and ragi in a dense recipe with a gently roasted grain character.",
    descriptionTa: "டார்க் காகாவும் ராகியும் இணையும் அடர்த்தியான பிரௌனி.",
    price: "Select a format",
    status: "validation",
    image: "/images/ragi-brownie-hero.png",
    format: "Egg or Eggless",
  },
  {
    id: "walnut-reserve",
    category: "signature",
    name: "Walnut Reserve",
    nameTa: "வால்நட் ரிசர்வ்",
    description: "Dark chocolate brownie with toasted walnut through every generous piece.",
    descriptionTa: "ஒவ்வொரு துண்டிலும் வறுத்த வால்நட்டுடன் டார்க் சாக்லேட் பிரௌனி.",
    price: "Select a format",
    status: "validation",
    image: "/images/brownie-closeup.png",
    format: "Egg or Eggless",
  },
  {
    id: "pista-rose-cardamom",
    category: "signature",
    name: "Pista, Rose & Cardamom",
    nameTa: "பிஸ்தா, ரோஸ் & ஏலக்காய்",
    description: "Pistachio richness, warm cardamom and a restrained rose finish over dark cacao.",
    descriptionTa: "டார்க் காகாவுடன் பிஸ்தா, ரோஸ் மற்றும் ஏலக்காய் அளவாக இணையும் பிரௌனி.",
    price: "Select a format",
    status: "validation",
    image: "/images/brownie-tins.png",
    format: "Egg or Eggless",
  },
  {
    id: "biscoff-crunch",
    category: "classics",
    name: "Biscoff Crunch Brownie",
    nameTa: "பிஸ்காஃப் கிரஞ்ச் பிரௌனி",
    description: "A limited celebration brownie with caramelised biscuit crunch.",
    descriptionTa: "கரமேலைஸ் செய்யப்பட்ட பிஸ்கட் கிரஞ்சுடன் கொண்டாட்ட பிரௌனி.",
    price: "Format price + premium",
    status: "coming-soon",
    image: "/images/brownie-tins.png",
    format: "Ingredient verification required",
  },
  {
    id: "chocolate-wafer-crunch",
    category: "classics",
    name: "Chocolate Wafer Crunch Brownie",
    nameTa: "சாக்லேட் வேஃபர் கிரஞ்ச் பிரௌனி",
    description: "A playful chocolate-led finish with crisp wafer contrast.",
    descriptionTa: "மொறுமொறுப்பான வேஃபர் அமைப்புடன் சாக்லேட் பிரௌனி.",
    price: "Format price + premium",
    status: "coming-soon",
    image: "/images/brownie-tins.png",
    format: "Ingredient verification required",
  },
  {
    id: "strawberry-cacao",
    category: "classics",
    name: "Seasonal Strawberry & Cacao Brownie",
    nameTa: "பருவகால ஸ்ட்ராபெரி & காகாவ் பிரௌனி",
    description: "Fresh strawberry and dark cacao, offered only when sourcing and cold-chain tests pass.",
    descriptionTa: "சோர்சிங் மற்றும் குளிர்சாதன சோதனைக்குப் பிறகு மட்டுமே கிடைக்கும் ஸ்ட்ராபெரி–காகாவ் பிரௌனி.",
    price: "Seasonal pricing",
    status: "seasonal",
    image: "/images/brownie-tins.png",
    format: "Limited dates",
  },
  {
    id: "signature-discovery-box",
    category: "boxes",
    name: "Signature Discovery Box — 6 pieces",
    nameTa: "சிக்னேச்சர் டிஸ்கவரி பாக்ஸ் — 6 துண்டுகள்",
    description: "Six generous pieces selected to introduce the San Bakes signature.",
    descriptionTa: "San Bakes சிக்னேச்சரை அறிமுகப்படுத்தும் ஆறு பிரௌனி துண்டுகள்.",
    price: "₹1,090",
    status: "validation",
    image: "/images/brownie-closeup.png",
    format: "Egg or Eggless",
  },
  {
    id: "reserve-collection",
    category: "boxes",
    name: "Reserve Collection — 9 pieces",
    nameTa: "ரிசர்வ் கலெக்ஷன் — 9 துண்டுகள்",
    description: "Nine generous pieces for a table, celebration or premium gift.",
    descriptionTa: "கொண்டாட்டம் அல்லது பிரீமியம் பரிசுக்கான ஒன்பது பிரௌனி துண்டுகள்.",
    price: "₹1,590",
    status: "validation",
    image: "/images/brownie-closeup.png",
    format: "Egg or Eggless",
  },
  {
    id: "tin-dark-cacao",
    category: "tins",
    name: "Dark Cacao Brownie Tin",
    nameTa: "டார்க் காகாவ் பிரௌனி டின்",
    description: "A generous brownie presentation in a slim tin with a restrained cacao finish.",
    descriptionTa: "மெல்லிய டினில் அளவான காகாவ் அலங்காரத்துடன் பிரௌனி.",
    price: "Planning from ₹590",
    status: "validation",
    image: "/images/brownie-tins.png",
    format: "Egg or Eggless",
  },
  {
    id: "tin-pista",
    category: "tins",
    name: "Pista, Rose & Cardamom Brownie Tin",
    nameTa: "பிஸ்தா, ரோஸ் & ஏலக்காய் பிரௌனி டின்",
    description: "A pistachio-led tin finished with measured rose and cardamom.",
    descriptionTa: "பிஸ்தா, ரோஸ் மற்றும் ஏலக்காயுடன் பிரௌனி டின்.",
    price: "Planning from ₹690",
    status: "validation",
    image: "/images/brownie-tins.png",
    format: "Egg or Eggless",
  },
  {
    id: "tin-strawberry",
    category: "tins",
    name: "Seasonal Strawberry & Cacao Brownie Tin",
    nameTa: "பருவகால ஸ்ட்ராபெரி & காகாவ் பிரௌனி டின்",
    description: "A seasonal tin for validated fruit and delivery conditions.",
    descriptionTa: "சோதிக்கப்பட்ட பழங்கள் மற்றும் டெலிவரி நிலைகளுக்கான பருவகால டின்.",
    price: "Planning from ₹750",
    status: "seasonal",
    image: "/images/brownie-tins.png",
    format: "Limited dates",
  },
  {
    id: "tin-classics",
    category: "tins",
    name: "Celebration Classics Brownie Tin",
    nameTa: "கொண்டாட்ட கிளாசிக்ஸ் பிரௌனி டின்",
    description: "A limited tin using clearly declared biscuit or confectionery finishes.",
    descriptionTa: "தெளிவாக அறிவிக்கப்பட்ட பிஸ்கட் அல்லது கான்ஃபெக்ஷனரி அலங்காரங்களுடன் டின்.",
    price: "Planning from ₹790",
    status: "coming-soon",
    image: "/images/brownie-tins.png",
    format: "Ingredient verification required",
  },
  {
    id: "classic-brownie-tub",
    category: "tubs",
    name: "Classic Brownie Tub",
    nameTa: "கிளாசிக் பிரௌனி டப்",
    description: "Brownie pieces in a round kraft tub with a chocolate-led drizzle.",
    descriptionTa: "சாக்லேட் டிரிசிலுடன் கிராஃப்ட் பேப்பர் டப்பில் பிரௌனி துண்டுகள்.",
    price: "Price after validation",
    status: "coming-soon",
    image: "/images/brownie-tubs.png",
    format: "Recipe details pending",
  },
  {
    id: "loaded-brownie-tub",
    category: "tubs",
    name: "Loaded Brownie Tub",
    nameTa: "லோடெட் பிரௌனி டப்",
    description: "A celebratory tub with chocolate drizzle, walnut and declared confectionery finishes.",
    descriptionTa: "சாக்லேட் டிரிசில், வால்நட் மற்றும் அறிவிக்கப்பட்ட கான்ஃபெக்ஷனரி அலங்காரங்களுடன் டப்.",
    price: "Price after validation",
    status: "coming-soon",
    image: "/images/loaded-brownie-tub.png",
    format: "Allergen verification required",
  },
  {
    id: "ragi-cacao-tea-cake",
    category: "tea-cakes",
    name: "Ragi Dark Cacao Tea Cake",
    nameTa: "ராகி டார்க் காகாவ் டீ கேக்",
    description: "Ragi and dark cacao in a soft, gently structured loaf with restrained sweetness.",
    descriptionTa: "ராகி மற்றும் டார்க் காகாவுடன் அளவான இனிப்பில் மென்மையான லோஃப் கேக்.",
    price: "Planning from ₹850",
    status: "coming-soon",
    format: "Egg or Eggless after testing",
  },
  {
    id: "pista-cardamom-tea-cake",
    category: "tea-cakes",
    name: "Pista Cardamom Millet Tea Cake",
    nameTa: "பிஸ்தா ஏலக்காய் சிறுதானிய டீ கேக்",
    description: "A millet-led tea cake with pistachio richness and a measured cardamom finish.",
    descriptionTa: "பிஸ்தாவின் செறிவும் அளவான ஏலக்காய் மணமும் கொண்ட டீ கேக்.",
    price: "Planning from ₹950",
    status: "coming-soon",
    format: "Egg or Eggless after testing",
  },
  {
    id: "birthday-250",
    category: "celebrations",
    name: "Little Celebration — 250 g",
    nameTa: "லிட்டில் செலிப்ரேஷன் — 250 கிராம்",
    description: "A compact brownie cake for a quiet birthday or two-to-four-person celebration.",
    descriptionTa: "இரண்டு முதல் நான்கு பேர் கொண்ட சிறிய கொண்டாட்டத்திற்கான பிரௌனி கேக்.",
    price: "From ₹950",
    status: "validation",
    format: "Egg or Eggless · 72-hour lead time",
  },
  {
    id: "birthday-500",
    category: "celebrations",
    name: "The Celebration — 500 g",
    nameTa: "தி செலிப்ரேஷன் — 500 கிராம்",
    description: "Our signature brownie birthday cake with a restrained finish and short message.",
    descriptionTa: "அளவான அலங்காரமும் குறுகிய வாழ்த்தும் கொண்ட பிரௌனி பிறந்தநாள் கேக்.",
    price: "From ₹1,750",
    status: "validation",
    image: "/images/birthday-cake-500g.jpg",
    format: "Egg or Eggless · 72-hour lead time",
  },
  {
    id: "birthday-1kg",
    category: "celebrations",
    name: "The Grand Celebration — 1 kg",
    nameTa: "தி கிராண்ட் செலிப்ரேஷன் — 1 கிலோ",
    description: "A generous square brownie cake for a fuller birthday gathering.",
    descriptionTa: "பெரிய கொண்டாட்டத்திற்கான சதுர பிரௌனி பிறந்தநாள் கேக்.",
    price: "From ₹3,150",
    status: "validation",
    image: "/images/birthday-cake-1kg.jpg",
    format: "Egg or Eggless · 4-day lead time",
  },
  {
    id: "mini-brownie-tower",
    category: "celebrations",
    name: "Mini Brownie Tower",
    nameTa: "மினி பிரௌனி டவர்",
    description: "Stacked brownie pieces with a restrained drizzle and optional approved topper.",
    descriptionTa: "அளவான டிரிசில் மற்றும் விருப்பமான டாப்பருடன் அடுக்கப்படும் பிரௌனி துண்டுகள்.",
    price: "From ₹1,390",
    status: "coming-soon",
    image: "/images/mini-brownie-tower.jpg",
    format: "Pickup recommended during validation",
  },
  {
    id: "cupcake-ragi",
    category: "cupcakes",
    name: "Dark Cacao Ragi Cupcake Collection",
    nameTa: "டார்க் காகாவ் ராகி கப் கேக் தொகுப்பு",
    description: "Six small-batch cupcakes with a restrained cacao finish.",
    descriptionTa: "அளவான காகாவ் அலங்காரத்துடன் ஆறு கப் கேக்குகள்.",
    price: "Planning ₹1,290 per six",
    status: "coming-soon",
    format: "Phase two · stability test pending",
  },
  {
    id: "cupcake-pista",
    category: "cupcakes",
    name: "Pista Cardamom Cupcake Collection",
    nameTa: "பிஸ்தா ஏலக்காய் கப் கேக் தொகுப்பு",
    description: "Six cupcakes with pistachio and a low-sweetness cardamom finish.",
    descriptionTa: "பிஸ்தா மற்றும் அளவான ஏலக்காய் அலங்காரத்துடன் ஆறு கப் கேக்குகள்.",
    price: "Planning ₹1,290 per six",
    status: "coming-soon",
    format: "Phase two · stability test pending",
  },
  {
    id: "corporate-mini-box",
    category: "gifting",
    name: "Corporate Mini Box — 4 pieces",
    nameTa: "கார்ப்பரேட் மினி பாக்ஸ் — 4 துண்டுகள்",
    description: "A compact employee or client gift with controlled flavour options.",
    descriptionTa: "ஊழியர்கள் அல்லது வாடிக்கையாளர்களுக்கான நான்கு துண்டு பரிசுப் பெட்டி.",
    price: "Planning ₹690 · volume quotation",
    status: "quotation",
    image: "/images/brownie-closeup.png",
    format: "Minimum order applies",
  },
  {
    id: "seasonal-hamper",
    category: "gifting",
    name: "Seasonal Hamper",
    nameTa: "பருவகால ஹாம்பர்",
    description: "A limited festival composition selected around verified products and packaging.",
    descriptionTa: "சோதிக்கப்பட்ட தயாரிப்புகள் மற்றும் பேக்கிங்குடன் பருவகால பரிசுத் தொகுப்பு.",
    price: "Planning ₹1,990–₹2,990",
    status: "seasonal",
    image: "/images/brownie-tins.png",
    format: "Limited edition",
  },
  {
    id: "bespoke-corporate",
    category: "gifting",
    name: "Bespoke Corporate Gifting",
    nameTa: "தனிப்பயன் நிறுவன பரிசுகள்",
    description: "Structured gifting for teams and clients, with quantity and branding controls.",
    descriptionTa: "அளவு மற்றும் பிராண்டிங் கட்டுப்பாடுகளுடன் நிறுவன பரிசுகள்.",
    price: "By quotation",
    status: "quotation",
    format: "Minimum 25 boxes or ₹15,000",
  },
];

export const statusLabel: Record<ProductStatus, { en: string; ta: string }> = {
  validation: { en: "Launch validation", ta: "அறிமுக சோதனை" },
  "coming-soon": { en: "Coming soon", ta: "விரைவில் வருகிறது" },
  seasonal: { en: "Seasonal", ta: "பருவகாலம்" },
  quotation: { en: "By quotation", ta: "விலை மதிப்பீடு" },
};

export const findProduct = (id: string) => products.find((product) => product.id === id);
