import Link from "next/link";
import { decisionLabel, directPlanningPriceIds, formatPrice, getPricing, priceRevisionExclusions, priceRevisionPercent } from "../lib/pricing";
import { products } from "../lib/products";

const validationGroups = [
  { title:"Brownie Tins", recommendation:"Use one three-piece Tin at ₹549–₹649 and a 2/3/5-Tin Flight at ₹1,190/₹1,740/₹2,850. Each Tin may be one flavour or kitchen-curated assorted.", checks:"Final piece and net weight, divider/liner, packaging cost, five-flavour availability, storage and 10/20 km condition test." },
  { title:"Brownie Tubs", recommendation:"Use ₹382 Classic and ₹467 Loaded for one target-250 g tub after the 15% base-price revision.", checks:"Actual net weight, chocolate/drizzle specification, topping allergens, kraft-tub seal, spoonability and margin." },
  { title:"Millet Tea Cakes", recommendation:"Use one target-450 g loaf: ₹723 Ragi Dark Cacao and ₹808 Pista Cardamom; offer a two-loaf gift duo only.", checks:"Exact millet quantity, baked yield, slice count, shelf life, loaf packaging and supplier prices." },
  { title:"Cupcakes", recommendation:"Launch only in boxes of 6 or 12; ₹1,097/₹2,117 for Ragi and ₹1,182/₹2,287 for Pista.", checks:"Frosting stability, two-hour ambient test, 20 km transport test, insert fit and remake rate." },
  { title:"Celebration Classics & Strawberry", recommendation:"Keep them limited rather than part of the ingredient-led flagship collection.", checks:"Brand-specific ingredient panels, allergens, fresh-fruit sourcing, cold-chain risk and seasonal availability." },
  { title:"Birthday Brownie Cakes", recommendation:"Approve classic and reserve-nut finishes only; include one short message and charge for toppers separately.", checks:"Finished net weight, serving guide, message limit, board/box cost and route suitability by size." },
];

export default function LaunchReviewPage() {
  const approveCount = products.filter((product) => getPricing(product.id).decision === "approve").length;
  const conditionalCount = products.filter((product) => getPricing(product.id).decision === "conditional").length;
  const revisedLegacyCount = products.filter((product) => !priceRevisionExclusions.has(product.id) && !directPlanningPriceIds.has(product.id)).length;
  return <main className="reviewPage"><section className="reviewHero"><p className="eyebrow">OWNER-ONLY WORKING PAGE · DO NOT PUBLISH</p><h1>Menu, quantity and pricing approval.</h1><p>This page records the revised commercial structure. Legacy consumer recommendations are 15% below the previous proposal, rounded to the nearest rupee. The restructured three-piece Tin and Tin Flight use direct planning prices; Corporate Mini Box, Seasonal Hamper and Bespoke Corporate Gifting remain unchanged.</p><div className="reviewHeroActions"><Link className="button buttonLight" href="/menu">Open customer menu</Link><Link className="button buttonOutlineLight" href="/preorder">Test preorder flow</Link></div></section>
    <section className="reviewSection"><div className="domainStatus"><span>DOMAIN PURCHASE STATUS</span><strong>sanbakes.com · sanbakes.in · sanbakes.co.in</strong><p>Purchased for two years. Registration is in progress; DNS and custom-domain connection have not been activated.</p></div><div className="reviewSummary"><article><small>RECOMMEND APPROVAL</small><strong>{approveCount} products</strong><span>Core brownies, boxes and standard birthday cakes</span></article><article><small>CONDITIONAL</small><strong>{conditionalCount} products</strong><span>Price proposed; validation gates remain</span></article><article><small>PRICE REVISION</small><strong>{priceRevisionPercent}% lower</strong><span>Applied to {revisedLegacyCount} legacy products; Tins priced directly; three gifting categories unchanged</span></article><article><small>EGG / EGGLESS</small><strong>Same launch price</strong><span>Recommended: no Eggless surcharge</span></article></div>
      <div className="reviewDecision"><div><p className="eyebrow dark">RECOMMENDED COMMERCIAL RULES</p><h2>Approve the system, not just isolated prices.</h2></div><ol><li><strong>Same price for Egg and Eggless</strong><span>Separate recipes and capacity records, but no customer-facing surcharge at launch.</span></li><li><strong>Delivery charged separately</strong><span>Pass through the approved live courier quote; do not hide it inside product prices.</span></li><li><strong>One short cake message included</strong><span>Reserve-nut finish, toppers, sleeves, artwork and complex changes are paid additions.</span></li><li><strong>15% base-price revision</strong><span>Treat the revised values as the new recommendations, not as public discount messaging. The three excluded gifting categories remain unchanged.</span></li><li><strong>Re-cost at a 5% input change</strong><span>Review chocolate, pistachio, walnut and packaging costs monthly during validation.</span></li></ol></div>
      <div className="reviewTableWrap"><div className="reviewTableHead"><p className="eyebrow dark">COMPLETE REVISED PROPOSAL</p><h2>Every item and sellable option.</h2><p>Previous recommendations are struck through where the 15% revision applies. Prices exclude delivery and paid customisation.</p></div><div className="reviewTable"><div className="reviewRow reviewColumns"><span>Product</span><span>Recommendation</span><span>Pack / quantity options</span><span>Owner decision</span></div>{products.map((product) => { const pricing=getPricing(product.id); return <div className="reviewRow" key={product.id}><span><strong>{product.name}</strong><small>{product.format}</small></span><span><em className={`reviewStatus ${pricing.decision}`}>{decisionLabel[pricing.decision].en}</em></span><span>{pricing.options.map((item) => <span className="reviewOption" key={item.id}><b>{item.label}</b><span className="reviewPrice">{item.originalPrice !== undefined && <del>{formatPrice(item.originalPrice)}</del>}<strong>{formatPrice(item.price)}</strong></span><small>{item.note}</small></span>)}</span><span><i>Pending owner approval</i></span></div>; })}</div></div>
      <div className="validationSection"><div><p className="eyebrow dark">PENDING PRODUCT GATES</p><h2>What must be checked before “available” replaces “coming soon.”</h2></div><div className="validationGrid">{validationGroups.map((group,index) => <article key={group.title}><span>{String(index+1).padStart(2,"0")}</span><h3>{group.title}</h3><strong>Recommendation</strong><p>{group.recommendation}</p><strong>Approve after</strong><p>{group.checks}</p></article>)}</div></div>
      <div className="approvalPrompt"><div><p className="eyebrow">SUGGESTED APPROVAL RESPONSE</p><h2>Review, then approve by group.</h2><p>Reply in the Codex task with: “Approve revised core prices”, followed by any conditional groups you approve—for example “Approve Tubs at ₹382/₹467 after 250 g validation.” Changes can be named item by item.</p></div><Link className="button buttonLight" href="/menu">Review the customer menu</Link></div>
    </section></main>;
}
