import Link from "next/link";
import { decisionLabel, formatPrice, getPricing } from "../lib/pricing";
import { products } from "../lib/products";

const validationGroups = [
  { title:"Brownie Tins", recommendation:"Keep the target at one 300 g tin and approve ₹590–₹790 only after the production tin is weighed.", checks:"Final net weight, pan yield, topping cost, storage and 10/20 km route test." },
  { title:"Brownie Tubs", recommendation:"Replace the historical ₹299/₹349 with ₹449 Classic and ₹549 Loaded for one target-250 g tub.", checks:"Actual net weight, chocolate/drizzle specification, topping allergens, kraft-tub seal, spoonability and margin." },
  { title:"Millet Tea Cakes", recommendation:"Use one target-450 g loaf: ₹850 Ragi Dark Cacao and ₹950 Pista Cardamom; offer a two-loaf gift duo only.", checks:"Exact millet quantity, baked yield, slice count, shelf life, loaf packaging and supplier prices." },
  { title:"Cupcakes", recommendation:"Launch only in boxes of 6 or 12; ₹1,290/₹2,490 for Ragi and ₹1,390/₹2,690 for Pista.", checks:"Frosting stability, two-hour ambient test, 20 km transport test, insert fit and remake rate." },
  { title:"Celebration Classics & Strawberry", recommendation:"Keep them limited rather than part of the ingredient-led flagship collection.", checks:"Brand-specific ingredient panels, allergens, fresh-fruit sourcing, cold-chain risk and seasonal availability." },
  { title:"Birthday Brownie Cakes", recommendation:"Approve classic and reserve-nut finishes only; include one short message and charge for toppers separately.", checks:"Finished net weight, serving guide, message limit, board/box cost and route suitability by size." },
];

export default function LaunchReviewPage() {
  const approveCount = products.filter((product) => getPricing(product.id).decision === "approve").length;
  const conditionalCount = products.filter((product) => getPricing(product.id).decision === "conditional").length;
  const quotationCount = products.filter((product) => getPricing(product.id).decision === "quotation").length;
  return <main className="reviewPage"><section className="reviewHero"><p className="eyebrow">OWNER-ONLY WORKING PAGE · DO NOT PUBLISH</p><h1>Menu, quantity and pricing approval.</h1><p>This page records the recommended commercial structure. “Approve” means the price architecture is suitable for launch planning—not that a product can be sold before its recipe, label, FSSAI and operational checks pass.</p><div className="reviewHeroActions"><Link className="button buttonLight" href="/menu">Open customer menu</Link><Link className="button buttonOutlineLight" href="/preorder">Test preorder flow</Link></div></section>
    <section className="reviewSection"><div className="reviewSummary"><article><small>RECOMMEND APPROVAL</small><strong>{approveCount} products</strong><span>Core brownies, boxes and standard birthday cakes</span></article><article><small>CONDITIONAL</small><strong>{conditionalCount} products</strong><span>Price proposed; validation gates remain</span></article><article><small>QUOTATION</small><strong>{quotationCount} products</strong><span>Corporate volume and bespoke work</span></article><article><small>EGG / EGGLESS</small><strong>Same launch price</strong><span>Recommended: no Eggless surcharge</span></article></div>
      <div className="reviewDecision"><div><p className="eyebrow dark">RECOMMENDED COMMERCIAL RULES</p><h2>Approve the system, not just isolated prices.</h2></div><ol><li><strong>Same price for Egg and Eggless</strong><span>Separate recipes and capacity records, but no customer-facing surcharge at launch.</span></li><li><strong>Delivery charged separately</strong><span>Pass through the approved live courier quote; do not hide it inside product prices.</span></li><li><strong>One short cake message included</strong><span>Reserve-nut finish, toppers, sleeves, artwork and complex changes are paid additions.</span></li><li><strong>No launch discounts</strong><span>Use premium value, limited capacity and reliable handover; protect the contribution-margin floor.</span></li><li><strong>Re-cost at a 5% input change</strong><span>Review chocolate, pistachio, walnut and packaging costs monthly during validation.</span></li></ol></div>
      <div className="reviewTableWrap"><div className="reviewTableHead"><p className="eyebrow dark">COMPLETE PROPOSAL</p><h2>Every item and sellable option.</h2><p>Prices exclude delivery and paid customisation.</p></div><div className="reviewTable"><div className="reviewRow reviewColumns"><span>Product</span><span>Recommendation</span><span>Pack / quantity options</span><span>Owner decision</span></div>{products.map((product) => { const pricing=getPricing(product.id); return <div className="reviewRow" key={product.id}><span><strong>{product.name}</strong><small>{product.format}</small></span><span><em className={`reviewStatus ${pricing.decision}`}>{decisionLabel[pricing.decision].en}</em></span><span>{pricing.options.map((item) => <span className="reviewOption" key={item.id}><b>{item.label}</b><strong>{formatPrice(item.price)}</strong><small>{item.note}</small></span>)}</span><span><i>Pending owner approval</i></span></div>; })}</div></div>
      <div className="validationSection"><div><p className="eyebrow dark">PENDING PRODUCT GATES</p><h2>What must be checked before “available” replaces “coming soon.”</h2></div><div className="validationGrid">{validationGroups.map((group,index) => <article key={group.title}><span>{String(index+1).padStart(2,"0")}</span><h3>{group.title}</h3><strong>Recommendation</strong><p>{group.recommendation}</p><strong>Approve after</strong><p>{group.checks}</p></article>)}</div></div>
      <div className="approvalPrompt"><div><p className="eyebrow">SUGGESTED APPROVAL RESPONSE</p><h2>Review, then approve by group.</h2><p>Reply in the Codex task with: “Approve core prices”, followed by any conditional groups you approve—for example “Approve Tubs at ₹449/₹549 after 250 g validation.” Changes can be named item by item.</p></div><Link className="button buttonLight" href="/menu">Review the customer menu</Link></div>
    </section></main>;
}
