"use client";

import Image from "next/image";
import { useLanguage } from "../components/LanguageProvider";

export default function AboutPage() {
  const { language } = useLanguage();
  const en = language === "en";
  return <main>
    <section className="innerHero aboutHero"><p className="eyebrow">WHY SAN BAKES</p><h1>{en ? "Premium is a standard, not a garnish." : "பிரீமியம் என்பது அலங்காரம் அல்ல; அது ஒரு தரநிலை."}</h1><p>{en ? "San Bakes is a preorder-led home bakery in Keelkattalai, Chennai—built around careful recipes, controlled batches and honest communication." : "San Bakes என்பது கீழ்க்கட்டளை, சென்னையில் உள்ள முன்பதிவு ஹோம் பேக்கரி—கவனமான ரெசிபிகள், கட்டுப்படுத்தப்பட்ட தொகுதிகள் மற்றும் நேர்மையான தகவல் இதன் அடித்தளம்."}</p></section>
    <section className="editorialSplit"><div className="editorialImage"><Image src="/images/editorial/about-kitchen-philosophy-v1.webp" alt="San Bakes brownie batch being carefully portioned" fill sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="editorialCopy"><p className="eyebrow dark">THE KITCHEN PHILOSOPHY</p><h2>{en ? "Less noise. More attention." : "குறைந்த சத்தம். அதிக கவனம்."}</h2><p>{en ? "Preorders give a home kitchen something mass retail cannot: time to plan ingredients, batch size and the handover. That discipline—not excess decoration—is the foundation of the premium experience." : "முன்பதிவு மூலம் பொருட்கள், தொகுதி அளவு மற்றும் ஹேண்ட்ஓவரை திட்டமிட நேரம் கிடைக்கிறது. அதுவே பிரீமியம் அனுபவத்தின் அடித்தளம்."}</p><p>{en ? "We are developing signature recipes around dark cacao, ragi, walnut, pistachio and cardamom. Final ingredient panels and nutrition or wellness claims will be published only after recipe testing and label verification." : "டார்க் காகாவ், ராகி, வால்நட், பிஸ்தா மற்றும் ஏலக்காயை மையமாகக் கொண்ட சிக்னேச்சர் ரெசிபிகள் உருவாக்கப்படுகின்றன. சோதனைக்குப் பிறகே இறுதி விவரங்கள் வெளியிடப்படும்."}</p></div></section>
    <section className="principlesSection"><p className="eyebrow dark">WHAT TRUST LOOKS LIKE</p><h2>{en ? "Five promises we can keep." : "நாங்கள் காப்பாற்றக்கூடிய ஐந்து வாக்குறுதிகள்."}</h2><div className="principleGrid"><article><span>01</span><h3>{en ? "Clear formulation" : "தெளிவான வகை"}</h3><p>{en ? "Every product can be selected as Regular (with egg) or Eggless, and that recipe choice stays with the cart line and confirmation." : "ஒவ்வொரு தயாரிப்பையும் வழக்கமானது (முட்டையுடன்) அல்லது முட்டையில்லா வகையாகத் தேர்ந்தெடுக்கலாம்; அந்த ரெசிபி தேர்வு கார்ட் மற்றும் உறுதிப்படுத்தலில் தெளிவாக இருக்கும்."}</p></article><article><span>02</span><h3>{en ? "Declared allergens" : "அலர்ஜன் தகவல்"}</h3><p>{en ? "Wheat, milk, egg, nuts and soy handling is disclosed before confirmation." : "கோதுமை, பால், முட்டை, நட்ஸ் மற்றும் சோயா முன்கூட்டியே அறிவிக்கப்படும்."}</p></article><article><span>03</span><h3>{en ? "Measured claims" : "அளவான கூற்றுகள்"}</h3><p>{en ? "No “guilt-free”, “chemical-free” or medical language—only claims supported by final recipes." : "ஆதாரமற்ற ஆரோக்கிய அல்லது மருத்துவ கூற்றுகள் இல்லை."}</p></article><article><span>04</span><h3>{en ? "Protected capacity" : "கட்டுப்படுத்தப்பட்ட திறன்"}</h3><p>{en ? "A proposed starting ceiling of 12–16 standard boxes or 4 celebration cakes per production day." : "ஒரு தயாரிப்பு நாளுக்கு 12–16 பெட்டிகள் அல்லது 4 கொண்டாட்ட கேக்குகள் என்ற தொடக்க வரம்பு."}</p></article><article><span>05</span><h3>{en ? "Traceable batches" : "கண்காணிக்கக்கூடிய தொகுதிகள்"}</h3><p>{en ? "Every confirmed order should carry a batch date, formulation and storage note." : "ஒவ்வொரு ஆர்டரிலும் தொகுதி தேதி, வகை மற்றும் சேமிப்பு குறிப்பு இருக்கும்."}</p></article></div></section>
    <section className="licenseCallout"><div><p className="eyebrow">LAUNCH DISCLOSURE</p><h2>{en ? "FSSAI registration is in progress." : "FSSAI பதிவு நடைபெற்று வருகிறது."}</h2></div><p>{en ? "The current website accepts enquiries only. Transactional checkout and final consumer labelling should activate after the registration/licence number, entity name, recipes, shelf-life tests and supplier declarations are recorded." : "தற்போதைய இணையதளம் விசாரணைகளை மட்டுமே ஏற்கிறது. FSSAI மற்றும் இறுதி தயாரிப்பு விவரங்கள் பதிவு செய்யப்பட்ட பிறகே ஆன்லைன் விற்பனை தொடங்கும்."}</p></section>
    <section className="preorder compact"><h2>{en ? "Start with the collection." : "மெனுவில் தொடங்குங்கள்."}</h2><p>{en ? "Browse every proposed launch item and build one clear WhatsApp enquiry." : "அனைத்து தயாரிப்புகளையும் பார்த்து WhatsApp விசாரணையை உருவாக்குங்கள்."}</p><a className="button buttonCacao" href="/menu">{en ? "View the menu" : "மெனுவைப் பார்க்க"}</a></section>
  </main>;
}
