"use client";

import { useLanguage } from "../components/LanguageProvider";

const policies = [
  { title: "Preorder & capacity", titleTa: "முன்பதிவு & திறன்", body: "Standard brownie enquiries should arrive at least 48 hours ahead. Birthday, occasion and party orders need five calendar days; 50+ packed brownies or 20+ Tins/Tubs need seven days; custom branding and 100+ units need 10–14 days. Dates remain unreserved until San Bakes confirms availability and the deposit.", bodyTa: "சாதாரண பிரௌனிகளுக்கு குறைந்தது 48 மணி நேரம் தேவை. பிறந்தநாள், நிகழ்ச்சி மற்றும் பார்ட்டி ஆர்டர்களுக்கு ஐந்து நாட்கள்; 50+ தனித்தனி பிரௌனிகள் அல்லது 20+ டின்கள்/டப்களுக்கு ஏழு நாட்கள்; தனிப்பயன் பிராண்டிங் மற்றும் 100+ யூனிட்களுக்கு 10–14 நாட்கள் தேவை. San Bakes உறுதி செய்த பிறகே தேதி முன்பதிவு செய்யப்படும்." },
  { title: "Cancellation & reschedule", titleTa: "ரத்து & தேதி மாற்றம்", body: "Proposed launch rule: one reschedule may be offered where capacity permits. For party and corporate orders, quantities, flavours and artwork close on the confirmed deadline. Within 72 hours of handover, committed ingredient, printing and production costs are non-refundable. Fully customised or already-started orders are not refundable.", bodyTa: "திறன் இருந்தால் ஒரு முறை தேதி மாற்றம் வழங்கப்படலாம். பார்ட்டி மற்றும் நிறுவன ஆர்டர்களின் அளவு, சுவை மற்றும் வடிவமைப்பு உறுதி செய்யப்பட்ட கடைசி தேதியில் முடிக்கப்படும். ஹேண்ட்ஓவருக்கு 72 மணி நேரத்திற்குள் உறுதி செய்யப்பட்ட செலவுகள் திருப்ப முடியாது." },
  { title: "Delivery & failed handover", titleTa: "டெலிவரி & தோல்வியடைந்த ஹேண்ட்ஓவர்", body: "Delivery is available within Chennai after address and live fee validation. Addresses beyond 20 km carry an additional distance-based charge included in the confirmed order total. The customer must be reachable. Re-delivery, waiting or return-to-kitchen fees are chargeable; food safety may prevent a second attempt.", bodyTa: "முகவரி மற்றும் நேரடி கட்டணம் உறுதி செய்யப்பட்ட பிறகு சென்னை முழுவதும் டெலிவரி கிடைக்கும். 20 கி.மீ.க்கு அப்பால் கூடுதல் தூரக் கட்டணம் உறுதி செய்யப்பட்ட ஆர்டர் மொத்தத்தில் சேர்க்கப்படும். வாடிக்கையாளர் தொடர்பில் இருக்க வேண்டும்; மீண்டும் டெலிவரி கட்டணம் விதிக்கப்படலாம்." },
  { title: "Pickup", titleTa: "பிக்கப்", body: "Pickup is by confirmed appointment only. The exact residential handover point is shared privately after confirmation. Arrive within the agreed 15-minute window, bring an insulated bag for longer travel and transport cakes on a flat, air-conditioned surface.", bodyTa: "உறுதி செய்யப்பட்ட நேரத்தில் மட்டுமே பிக்கப். சரியான இடம் உறுதிப்படுத்திய பிறகு தனியாக பகிரப்படும். நீண்ட பயணத்திற்கு இன்சுலேட்டட் பையை பயன்படுத்தவும்." },
  { title: "Allergens & suitability", titleTa: "அலர்ஜன்கள் & பொருத்தம்", body: "Every product can be selected as Regular (with egg) or Eggless. Eggless describes the selected recipe, while the home kitchen still handles egg, wheat/gluten, milk, tree nuts, peanuts and soy; it is not presented as vegan or allergen-free. Gluten-aware products, if introduced, will not be suitable for coeliac disease unless independently validated.", bodyTa: "ஒவ்வொரு தயாரிப்பையும் வழக்கமானது (முட்டையுடன்) அல்லது முட்டையில்லா வகையாகத் தேர்ந்தெடுக்கலாம். முட்டையில்லா என்பது தேர்ந்தெடுத்த ரெசிபியை மட்டும் குறிக்கும்; ஹோம் கிச்சனில் முட்டை, கோதுமை/குளூட்டன், பால், நட்ஸ், வேர்க்கடலை மற்றும் சோயா கையாளப்படுவதால் இது வீகன் அல்லது அலர்ஜன் இல்லாததாகக் கூறப்படாது." },
  { title: "Quality concern & refund", titleTa: "தர குறைவு & பணத்தைத் திருப்புதல்", body: "Contact San Bakes within four hours of handover with the order reference, photographs and storage details. Validated product defects may receive replacement, credit or refund. Preference differences, late consumption or incorrect storage are not product defects.", bodyTa: "ஹேண்ட்ஓவரிலிருந்து நான்கு மணி நேரத்திற்குள் ஆர்டர் குறிப்பு, புகைப்படங்கள் மற்றும் சேமிப்பு விவரங்களுடன் தொடர்பு கொள்ளவும். உறுதி செய்யப்பட்ட தயாரிப்பு குறைபாடுகளுக்கு மாற்று, கிரெடிட் அல்லது பணத்தைத் திருப்புதல் வழங்கப்படலாம்." },
  { title: "UPI payment", titleTa: "UPI கட்டணம்", body: "Place the cart order through WhatsApp before paying. Use the checkout QR only after San Bakes confirms availability, delivery and the exact total in writing. Enter that confirmed amount, verify the San Bakes recipient name in the UPI app and retain the transaction reference. A QR scan or payment screenshot does not by itself confirm the production slot; San Bakes must acknowledge receipt.", bodyTa: "கட்டணம் செலுத்துவதற்கு முன் கார்ட் ஆர்டரை WhatsApp மூலம் அனுப்பவும். கிடைக்கும் நிலை, டெலிவரி மற்றும் சரியான மொத்தத்தை San Bakes எழுத்தில் உறுதி செய்த பிறகு மட்டும் செக்அவுட் QR-ஐ பயன்படுத்தவும். உறுதி செய்யப்பட்ட தொகையை உள்ளிட்டு, UPI செயலியில் San Bakes பெறுநர் பெயரை சரிபார்த்து பரிவர்த்தனை குறிப்பை வைத்திருக்கவும். QR ஸ்கேன் அல்லது கட்டண ஸ்கிரீன்ஷாட் மட்டும் தயாரிப்பு ஸ்லாட்டை உறுதி செய்யாது; San Bakes ரசீதை உறுதிப்படுத்த வேண்டும்." },
  { title: "Customer information", titleTa: "வாடிக்கையாளர் தகவல்", body: "Name, phone, address, order details and payment reference should be used only to quote, fulfil, support and account for the order. Access should be limited to authorised operators and required service partners; retention periods will be formalised before checkout launch.", bodyTa: "பெயர், தொலைபேசி, முகவரி மற்றும் ஆர்டர் விவரங்கள் ஆர்டரை நிறைவேற்றுவதற்கும் ஆதரிப்பதற்கும் மட்டுமே பயன்படுத்தப்படும்." },
];

export default function PoliciesPage() {
  const { language } = useLanguage(); const en = language === "en";
  return <main><section className="innerHero policiesHero"><p className="eyebrow">ORDER WITH CLARITY</p><h1>{en ? "Practical policies, before the celebration." : "கொண்டாட்டத்திற்கு முன் தெளிவான கொள்கைகள்."}</h1><p>{en ? "These are recommended launch rules and will be finalised with the registered business and FSSAI details before the public ordering launch." : "இவை பரிந்துரைக்கப்பட்ட அறிமுக விதிகள். பொதுவான ஆர்டர் அறிமுகத்திற்கு முன் பதிவு செய்யப்பட்ட நிறுவனம் மற்றும் FSSAI விவரங்களுடன் இறுதி செய்யப்படும்."}</p></section><section className="policySection"><div className="policyIntro"><p className="eyebrow dark">PROPOSED LAUNCH POLICY · VERSION 0.2</p><p>{en ? "Last drafted 30 August 2026. Final terms must display the registered entity, FSSAI details, grievance contact and confirmed logistics partners." : "30 ஆகஸ்ட் 2026 வரைவு. இறுதி விதிகளில் பதிவு செய்யப்பட்ட நிறுவனம், FSSAI மற்றும் தொடர்பு விவரங்கள் இடம்பெறும்."}</p></div><div className="policyGrid">{policies.map((policy, index) => <article key={policy.title}><span>{String(index + 1).padStart(2, "0")}</span><h2>{en ? policy.title : policy.titleTa}</h2><p>{en ? policy.body : policy.bodyTa}</p></article>)}</div><div className="policyContact"><strong>{en ? "Need a suitability check before ordering?" : "ஆர்டருக்கு முன் தகவல் வேண்டுமா?"}</strong><a href="https://wa.me/919940058623" target="_blank" rel="noreferrer">WhatsApp +91 99400 58623 ↗</a></div></section></main>;
}
