"use client";

import { useLanguage } from "../components/LanguageProvider";

const questions = [
  { q:"How early should I order?", qt:"எவ்வளவு முன்பாக ஆர்டர் செய்ய வேண்டும்?", a:"Standard brownies, Brownie Tins, Brownie Tubs, tea cakes and personal gifts need at least 48 hours. Cupcake boxes of 6 need at least three days; boxes of 9 or 12 and all birthday, occasion and party orders need five calendar days. Orders of 50+ packed brownies or 20+ Tins/Tubs need seven days. Corporate orders start at seven days; 50+ units need 10 days, while branded sleeves and multi-address delivery need 14–21 days. Dates may close earlier once fully booked.", at:"சாதாரண பிரௌனிகள், டின்கள், டப்கள், டீ கேக்குகள் மற்றும் தனிப்பட்ட பரிசுகளுக்கு குறைந்தது 48 மணி நேரம் தேவை. 6 கப் கேக் பெட்டிகளுக்கு மூன்று நாட்கள்; 9 அல்லது 12 கப் கேக் பெட்டிகள் மற்றும் பிறந்தநாள், நிகழ்ச்சி, பார்ட்டி ஆர்டர்களுக்கு ஐந்து நாட்கள் தேவை. 50+ தனித்தனி பிரௌனிகள் அல்லது 20+ டின்கள்/டப்களுக்கு ஏழு நாட்கள் தேவை. நிறுவன ஆர்டர்கள் ஏழு நாட்களிலிருந்து தொடங்கும்; 50+ யூனிட்களுக்கு 10 நாட்கள், பிராண்டட் ஸ்லீவ் மற்றும் பல முகவரி டெலிவரிக்கு 14–21 நாட்கள் தேவை." },
  { q:"Which formulation is available at launch?", qt:"அறிமுகத்தில் எந்த வகை கிடைக்கும்?", a:"The current menu uses egg. Relevant allergen information is confirmed with each order.", at:"தற்போதைய மெனுவில் முட்டை பயன்படுத்தப்படுகிறது. தொடர்புடைய அலர்ஜன் தகவல் ஒவ்வொரு ஆர்டருடனும் உறுதி செய்யப்படும்." },
  { q:"Are any products vegan?", qt:"வீகன் தயாரிப்புகள் உள்ளதா?", a:"No. Any future vegan item will be labelled explicitly; products without that label should not be treated as vegan.", at:"இல்லை. எதிர்காலத்தில் வீகன் தயாரிப்பு இருந்தால் அது தெளிவாக குறிக்கப்படும்; அந்த லேபிள் இல்லாத தயாரிப்புகளை வீகன் என்று கருத வேண்டாம்." },
  { q:"Are the bakes gluten-free?", qt:"குளூட்டன் இல்லாத தயாரிப்புகளா?", a:"No gluten-free claim is made. The kitchen handles wheat and gluten. Millet or ragi in a recipe does not make the finished product gluten-free.", at:"குளூட்டன் இல்லாததாக எந்தக் கூற்றும் செய்யப்படவில்லை. சமையலறையில் கோதுமை மற்றும் குளூட்டன் கையாளப்படுகிறது. ராகி அல்லது சிறுதானியம் இருப்பதால் மட்டும் தயாரிப்பு குளூட்டன் இல்லாததாகாது." },
  { q:"Are San Bakes products healthy?", qt:"San Bakes தயாரிப்புகள் ஆரோக்கியமானவையா?", a:"Brownies, cakes and cupcakes are indulgent foods. We avoid blanket health claims and share meaningful ingredients, portions and allergens so customers can make an informed choice.", at:"பிரௌனி, கேக் மற்றும் கப் கேக்குகள் இனிப்பு உணவுகள். பொதுவான ஆரோக்கியக் கூற்றுகளை தவிர்த்து, பொருட்கள், அளவு மற்றும் அலர்ஜன் தகவலைத் தெளிவாக வழங்குகிறோம்." },
  { q:"Do you use preservatives or artificial colours?", qt:"பாதுகாப்புப் பொருட்கள் அல்லது செயற்கை நிறங்கள் உள்ளதா?", a:"We do not use ‘no preservatives’ or ‘no artificial colours’ as a blanket promise across the menu. Please rely on the product-specific ingredient list confirmed with your order.", at:"முழு மெனுவிற்கும் ‘பாதுகாப்புப் பொருட்கள் இல்லை’ அல்லது ‘செயற்கை நிறங்கள் இல்லை’ என்று பொதுவான வாக்குறுதி வழங்குவதில்லை. உங்கள் ஆர்டருடன் உறுதி செய்யப்படும் தயாரிப்பு சார்ந்த பொருள் பட்டியலைப் பார்க்கவும்." },
  { q:"Is ragi used in every product?", qt:"ஒவ்வொரு தயாரிப்பிலும் ராகி உள்ளதா?", a:"No. Ragi is used only in products that name it, such as Ragi No. 01 and the Ragi Dark Cacao Tea Cake. Every final product description will identify the actual grain used.", at:"இல்லை. Ragi No. 01 மற்றும் ராகி டார்க் காகாவ் டீ கேக் போன்ற பெயரில் குறிப்பிடப்பட்ட தயாரிப்புகளில் மட்டுமே ராகி பயன்படுத்தப்படும்." },
  { q:"How sweet are the brownies?", qt:"பிரௌனிகள் எவ்வளவு இனிப்பாக இருக்கும்?", a:"The recipes are developed to keep cacao, grain, nut and spice character clear rather than maximise sweetness. Taste is personal, so use each product’s flavour description when choosing.", at:"அதிக இனிப்பை விட காகாவ், தானியம், நட்ஸ் மற்றும் மசாலா சுவை தெளிவாக இருக்கும்படி ரெசிபிகள் உருவாக்கப்படுகின்றன." },
  { q:"What is the shelf life?", qt:"எவ்வளவு நாட்கள் வைத்திருக்கலாம்?", a:"Follow the product-specific best-before date and storage instructions supplied with your order. Because formats differ, we do not publish one shelf-life estimate for the entire menu.", at:"உங்கள் ஆர்டருடன் வழங்கப்படும் தயாரிப்பு சார்ந்த best-before தேதி மற்றும் சேமிப்பு வழிமுறைகளைப் பின்பற்றவும். தயாரிப்பு வடிவங்கள் வேறுபடுவதால் முழு மெனுவிற்கும் ஒரே சேமிப்பு காலத்தை வெளியிடுவதில்லை." },
  { q:"Where do you deliver?", qt:"எங்கு டெலிவரி செய்கிறீர்கள்?", a:"Delivery is available within Chennai, subject to route serviceability and product safety. The approved courier charge is added to the order total; addresses beyond 20 km include an additional distance-based charge.", at:"சென்னை முழுவதும், பாதை சேவை மற்றும் தயாரிப்பு பாதுகாப்பைப் பொறுத்து டெலிவரி கிடைக்கும். உறுதி செய்யப்பட்ட கூரியர் கட்டணம் ஆர்டர் மொத்தத்தில் சேர்க்கப்படும்; 20 கி.மீ.க்கு அப்பால் கூடுதல் தூரக் கட்டணம் சேர்க்கப்படும்." },
  { q:"Can I pick up my order?", qt:"ஆர்டரை பிக்கப் செய்யலாமா?", a:"Yes, by confirmed appointment. The exact residential handover point is shared privately after the order is confirmed. Unplanned walk-ins are not accepted.", at:"ஆம், உறுதி செய்யப்பட்ட நேரத்தில் பிக்கப் செய்யலாம். ஆர்டர் உறுதிசெய்யப்பட்ட பிறகு சரியான ஹேண்ட்ஓவர் இடம் தனியாக பகிரப்படும்." },
  { q:"Can I change or cancel an order?", qt:"ஆர்டரை மாற்றவோ ரத்து செய்யவோ முடியுமா?", a:"For standard orders, 48+ hours’ notice provides the broadest options. For party and corporate orders, quantities, flavours and artwork close on the confirmed deadline; within 72 hours of handover, committed ingredient, printing and production costs are non-refundable. One reschedule may be offered subject to date availability.", at:"சாதாரண ஆர்டர்களுக்கு 48 மணி நேரத்திற்கு முன் தெரிவித்தால் அதிகமான வாய்ப்புகள் கிடைக்கும். பார்ட்டி மற்றும் நிறுவன ஆர்டர்களில் உறுதி செய்யப்பட்ட கடைசி தேதிக்குப் பிறகு அளவு, சுவை மற்றும் வடிவமைப்பு மாற்ற முடியாது; ஹேண்ட்ஓவருக்கு 72 மணி நேரத்திற்குள் உறுதி செய்யப்பட்ட செலவுகள் திருப்ப முடியாது. தேதி கிடைப்பைப் பொறுத்து ஒரு முறை மாற்று தேதி வழங்கப்படலாம்." },
  { q:"What if my order arrives damaged or incorrect?", qt:"ஆர்டர் சேதமடைந்தால் அல்லது தவறாக இருந்தால்?", a:"Contact San Bakes within four hours of handover with the order reference, clear photographs and storage details. If we confirm a product or delivery fault, we may offer a replacement, credit or refund as appropriate.", at:"ஹேண்ட்ஓவரிலிருந்து நான்கு மணி நேரத்திற்குள் ஆர்டர் குறிப்பு, தெளிவான புகைப்படங்கள் மற்றும் சேமிப்பு விவரங்களுடன் தொடர்பு கொள்ளவும். தயாரிப்பு அல்லது டெலிவரி தவறு உறுதி செய்யப்பட்டால், பொருத்தமான மாற்று, கிரெடிட் அல்லது ரீஃபண்ட் வழங்கப்படலாம்." },
  { q:"Do you take corporate orders?", qt:"நிறுவன ஆர்டர்கள் ஏற்கப்படுமா?", a:"Yes. Corporate orders start at 25 individually packed brownies. Standard presentation requires at least seven calendar days; branded sleeves, larger quantities and multi-address delivery require longer.", at:"ஆம். நிறுவன ஆர்டர்கள் தனித்தனியாக பேக் செய்யப்பட்ட 25 பிரௌனிகளிலிருந்து தொடங்கும். சாதாரண நிறுவனப் பேக்கிங்கிற்கு குறைந்தது ஏழு நாட்கள் தேவை; பிராண்டட் ஸ்லீவ், பெரிய அளவு மற்றும் பல முகவரி டெலிவரிக்கு கூடுதல் நேரம் தேவை." },
  { q:"What are the party-order minimums?", qt:"பார்ட்டி ஆர்டரின் குறைந்தபட்ச அளவு என்ன?", a:"Individually packed brownies start at 25 pieces. Brownie Tins—either three separate pieces or one whole brownie—and Brownie Tubs start at 10 units each. Cakes can be ordered separately in the listed sizes. Flavour count, delivery method and your date are confirmed before the order is reserved.", at:"தனித்தனியாக பேக் செய்யப்பட்ட பிரௌனிகள் 25 துண்டுகளிலிருந்து தொடங்கும். மூன்று தனித்தனி துண்டுகள் அல்லது ஒரு முழு பிரௌனி கொண்ட டின்கள் மற்றும் பிரௌனி டப்கள் தலா 10 யூனிட்களிலிருந்து தொடங்கும். பட்டியலிடப்பட்ட அளவுகளில் கேக்குகளை தனியாக ஆர்டர் செய்யலாம். சுவை எண்ணிக்கை, டெலிவரி முறை மற்றும் தேதி ஆர்டர் முன்பதிவுக்கு முன் உறுதி செய்யப்படும்." },
  { q:"How does UPI payment work?", qt:"UPI கட்டணம் எப்படி செயல்படும்?", a:"Add products to the cart and place the order through WhatsApp first. After San Bakes confirms availability, delivery and the exact payable amount, return to checkout, enter that confirmed total and generate the amount-linked UPI QR. Verify the recipient name in your UPI app before paying. Quotation items cannot generate a payment QR until their final price is agreed.", at:"பொருட்களை கார்ட்டில் சேர்த்து முதலில் WhatsApp மூலம் ஆர்டர் செய்யவும். கிடைக்கும் நிலை, டெலிவரி மற்றும் சரியான கட்டண தொகையை San Bakes உறுதி செய்த பிறகு செக்அவுட்டுக்கு திரும்பி அந்த தொகையை உள்ளிட்டு UPI QR உருவாக்கவும். செலுத்தும் முன் UPI செயலியில் பெறுநர் பெயரை சரிபார்க்கவும். இறுதி விலை ஒப்புக்கொள்ளும் வரை விலை மதிப்பீட்டு பொருட்களுக்கு QR உருவாக்க முடியாது." },
];

const faqStructuredData = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: questions.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
};

export default function FAQPage() {
  const { language } = useLanguage(); const en = language === "en";
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData).replace(/</g, "\\u003c") }} /><section className="innerHero faqHero"><p className="eyebrow">{en ? "QUESTIONS, ANSWERED CLEARLY" : "கேள்விகளுக்கு தெளிவான பதில்கள்"}</p><h1>{en ? "Everything to know before you reserve." : "முன்பதிவு செய்வதற்கு முன் தெரிந்துகொள்ள வேண்டியவை."}</h1><p>{en ? "Ingredients, allergens, timing, delivery, storage, changes and payment—without vague promises." : "பொருட்கள், அலர்ஜன்கள், நேரம், டெலிவரி, சேமிப்பு, மாற்றங்கள் மற்றும் கட்டணம்—தெளிவான பதில்களுடன்."}</p></section><section className="faqSection"><div className="faqIntro"><p className="eyebrow dark">SAN BAKES FAQ</p><h2>{en ? "Straight answers build trust." : "நேரான பதில்களே நம்பிக்கையை உருவாக்கும்."}</h2><p>{en ? "Final product labels and your confirmed order summary take priority if they contain more specific information." : "குறிப்பிட்ட தகவல் இருந்தால் இறுதி தயாரிப்பு லேபிளும் உறுதி செய்யப்பட்ட ஆர்டர் சுருக்கமும் முன்னுரிமை பெறும்."}</p></div><div className="faqList">{questions.map((item,index) => <details key={item.q} open={index===0}><summary><span>{String(index+1).padStart(2,"0")}</span><strong>{en ? item.q : item.qt}</strong><i>+</i></summary><p>{en ? item.a : item.at}</p></details>)}</div><div className="faqCta"><div><strong>{en ? "Still deciding?" : "இன்னும் முடிவு செய்யவில்லையா?"}</strong><span>{en ? "Send the product, date and dietary concern on WhatsApp." : "தயாரிப்பு, தேதி மற்றும் உணவு தொடர்பான கேள்வியை WhatsApp-ல் அனுப்புங்கள்."}</span></div><a className="button buttonCacao" href="https://wa.me/919940058623?text=Hello%20San%20Bakes%2C%20I%20have%20a%20question%20before%20placing%20a%20preorder." target="_blank" rel="noreferrer">{en ? "Ask on WhatsApp" : "WhatsApp-ல் கேட்க"}</a></div><p className="faqPolicyLink"><a href="/policies">{en ? "Read the complete order, cancellation and allergen policies →" : "முழு ஆர்டர், ரத்து மற்றும் அலர்ஜன் கொள்கைகளைப் படிக்க →"}</a></p></section></main>;
}
