"use client";

import { useLanguage } from "../components/LanguageProvider";

const questions = [
  { q:"How early should I order?", qt:"எவ்வளவு முன்பாக ஆர்டர் செய்ய வேண்டும்?", a:"Standard brownie enquiries need at least 48 hours. Birthday, occasion and party orders need five calendar days; 50+ packed brownies or 20+ Tins/Tubs need seven days; custom branding and 100+ units need 10–14 days. A date can close earlier when capacity is reserved.", at:"சாதாரண பிரௌனி விசாரணைகளுக்கு குறைந்தது 48 மணி நேரம் தேவை. பிறந்தநாள், நிகழ்ச்சி மற்றும் பார்ட்டி ஆர்டர்களுக்கு ஐந்து நாட்கள்; 50+ தனித்தனி பிரௌனிகள் அல்லது 20+ டின்கள்/டப்களுக்கு ஏழு நாட்கள்; தனிப்பயன் பிராண்டிங் மற்றும் 100+ யூனிட்களுக்கு 10–14 நாட்கள் தேவை." },
  { q:"Do you offer Egg and Eggless?", qt:"முட்டை மற்றும் முட்டையில்லா இரண்டும் உள்ளதா?", a:"Yes. They are separately developed recipes and must be selected in the enquiry. Eggless means no egg in that recipe; the same home kitchen also handles egg and is not an egg-allergen-free facility.", at:"ஆம். அவை தனித்தனியாக உருவாக்கப்பட்ட ரெசிபிகள். Eggless ரெசிபியில் முட்டை சேர்க்கப்படாது; ஆனால் அதே ஹோம் கிச்சனில் முட்டையும் கையாளப்படுகிறது." },
  { q:"Are any products vegan?", qt:"வீகன் தயாரிப்புகள் உள்ளதா?", a:"Not at launch unless a specific product is expressly labelled vegan after ingredient and process verification. Eggless does not automatically mean vegan because dairy or other animal-derived ingredients may still be present.", at:"அறிமுகத்தின் போது குறிப்பிட்ட தயாரிப்பு சரிபார்க்கப்பட்டு வீகன் என்று குறிக்கப்படாவிட்டால் இல்லை. Eggless என்பது தானாகவே வீகன் என்று பொருள் இல்லை." },
  { q:"Are the bakes gluten-free?", qt:"குளூட்டன் இல்லாத தயாரிப்புகளா?", a:"No gluten-free claim is made. The kitchen handles wheat and gluten. Millet or ragi in a recipe does not make the finished product gluten-free.", at:"குளூட்டன் இல்லாததாக எந்தக் கூற்றும் செய்யப்படவில்லை. சமையலறையில் கோதுமை மற்றும் குளூட்டன் கையாளப்படுகிறது. ராகி அல்லது சிறுதானியம் இருப்பதால் மட்டும் தயாரிப்பு குளூட்டன் இல்லாததாகாது." },
  { q:"Are San Bakes products healthy?", qt:"San Bakes தயாரிப்புகள் ஆரோக்கியமானவையா?", a:"Brownies, cakes and cupcakes are indulgent foods. We avoid blanket health claims. We identify meaningful ingredients, portions and allergens so customers can make an informed choice once final recipes are verified.", at:"பிரௌனி, கேக் மற்றும் கப் கேக்குகள் இனிப்பு உணவுகள். பொதுவான ஆரோக்கியக் கூற்றுகளை தவிர்த்து, சரிபார்க்கப்பட்ட பொருட்கள், அளவு மற்றும் அலர்ஜன் தகவலைத் தெளிவாக வழங்குவோம்." },
  { q:"Do you use preservatives or artificial colours?", qt:"பாதுகாப்புப் பொருட்கள் அல்லது செயற்கை நிறங்கள் உள்ளதா?", a:"The core recipes are being developed without added artificial preservatives or artificial colours. That wording will be used on a product only after its complete recipe and every supplier component have been checked. The final ingredient list is authoritative.", at:"முக்கிய ரெசிபிகள் சேர்க்கப்பட்ட செயற்கை பாதுகாப்புப் பொருட்கள் மற்றும் செயற்கை நிறங்கள் இல்லாமல் உருவாக்கப்படுகின்றன. முழு ரெசிபி மற்றும் சப்ளையர் பொருட்கள் சரிபார்க்கப்பட்ட பிறகே அந்தக் கூற்று பயன்படுத்தப்படும்." },
  { q:"Is ragi used in every product?", qt:"ஒவ்வொரு தயாரிப்பிலும் ராகி உள்ளதா?", a:"No. Ragi is used only in products that name it, such as Ragi No. 01 and the Ragi Dark Cacao Tea Cake. Every final product description will identify the actual grain used.", at:"இல்லை. Ragi No. 01 மற்றும் ராகி டார்க் காகாவ் டீ கேக் போன்ற பெயரில் குறிப்பிடப்பட்ட தயாரிப்புகளில் மட்டுமே ராகி பயன்படுத்தப்படும்." },
  { q:"How sweet are the brownies?", qt:"பிரௌனிகள் எவ்வளவு இனிப்பாக இருக்கும்?", a:"The recipes are developed to keep cacao, grain, nut and spice character clear rather than maximise sweetness. Taste is personal, so use each product’s flavour description when choosing.", at:"அதிக இனிப்பை விட காகாவ், தானியம், நட்ஸ் மற்றும் மசாலா சுவை தெளிவாக இருக்கும்படி ரெசிபிகள் உருவாக்கப்படுகின்றன." },
  { q:"What is the shelf life?", qt:"எவ்வளவு நாட்கள் வைத்திருக்கலாம்?", a:"A product-specific best-before date and storage instruction will be supplied after formal recipe and shelf-life validation. We will not publish an estimated shelf life as if it were tested.", at:"முறையான ரெசிபி மற்றும் சேமிப்பு சோதனைக்குப் பிறகு தயாரிப்புக்கான best-before தேதி மற்றும் சேமிப்பு வழிமுறை வழங்கப்படும்." },
  { q:"Where do you deliver?", qt:"எங்கு டெலிவரி செய்கிறீர்கள்?", a:"Within a maximum 20 km road radius from Keelkattalai, Chennai 600117, subject to route serviceability, product safety and an approved live courier quote.", at:"கீழ்க்கட்டளை, சென்னை 600117-இல் இருந்து சாலை வழியாக அதிகபட்சம் 20 கி.மீ. வரை, சேவை மற்றும் தயாரிப்பு பாதுகாப்பைப் பொறுத்து டெலிவரி." },
  { q:"Can I pick up my order?", qt:"ஆர்டரை பிக்கப் செய்யலாமா?", a:"Yes, by confirmed appointment. The exact residential handover point is shared privately after the order is confirmed. Unplanned walk-ins are not accepted.", at:"ஆம், உறுதி செய்யப்பட்ட நேரத்தில் பிக்கப் செய்யலாம். ஆர்டர் உறுதிசெய்யப்பட்ட பிறகு சரியான ஹேண்ட்ஓவர் இடம் தனியாக பகிரப்படும்." },
  { q:"Can I change or cancel an order?", qt:"ஆர்டரை மாற்றவோ ரத்து செய்யவோ முடியுமா?", a:"For standard orders, 48+ hours’ notice provides the broadest options. For party and corporate orders, quantities, flavours and artwork close on the confirmed deadline; within 72 hours of handover, committed ingredient, printing and production costs are non-refundable. One reschedule may be offered where capacity permits.", at:"சாதாரண ஆர்டர்களுக்கு 48 மணி நேரத்திற்கு முன் தெரிவித்தால் அதிகமான வாய்ப்புகள் கிடைக்கும். பார்ட்டி மற்றும் நிறுவன ஆர்டர்களில் உறுதி செய்யப்பட்ட கடைசி தேதிக்குப் பிறகு அளவு, சுவை மற்றும் வடிவமைப்பு மாற்ற முடியாது; ஹேண்ட்ஓவருக்கு 72 மணி நேரத்திற்குள் உறுதி செய்யப்பட்ட செலவுகள் திருப்ப முடியாது." },
  { q:"What if my order arrives damaged or incorrect?", qt:"ஆர்டர் சேதமடைந்தால் அல்லது தவறாக இருந்தால்?", a:"Contact San Bakes within four hours of handover with the order reference, clear photographs and storage details. A validated product or delivery fault may receive replacement, credit or refund.", at:"ஹேண்ட்ஓவரிலிருந்து நான்கு மணி நேரத்திற்குள் ஆர்டர் குறிப்பு, தெளிவான புகைப்படங்கள் மற்றும் சேமிப்பு விவரங்களுடன் தொடர்பு கொள்ளவும்." },
  { q:"Do you take corporate orders?", qt:"நிறுவன ஆர்டர்கள் ஏற்கப்படுமா?", a:"Yes. The recommended minimum is 25 four-piece boxes or ₹15,000 before delivery, whichever is reached first. Standard presentation starts at seven calendar days; branded and multi-address projects require longer.", at:"ஆம். குறைந்தபட்சம் 25 நான்கு-துண்டு பெட்டிகள் அல்லது டெலிவரிக்கு முன் ₹15,000. சாதாரண நிறுவனப் பேக்கிங்கிற்கு குறைந்தது ஏழு நாட்கள் தேவை." },
  { q:"What are the party-order minimums?", qt:"பார்ட்டி ஆர்டரின் குறைந்தபட்ச அளவு என்ன?", a:"Individually packed brownies start at 25 pieces. Three-piece Brownie Tins and Brownie Tubs start at 10 units each. Cakes can be ordered separately in the listed sizes. Final capacity, flavour count and transport method are confirmed before the slot is reserved.", at:"தனித்தனியாக பேக் செய்யப்பட்ட பிரௌனிகள் 25 துண்டுகளிலிருந்து தொடங்கும். மூன்று துண்டு பிரௌனி டின்கள் மற்றும் பிரௌனி டப்கள் தலா 10 யூனிட்களிலிருந்து தொடங்கும். பட்டியலிடப்பட்ட அளவுகளில் கேக்குகளை தனியாக ஆர்டர் செய்யலாம்." },
  { q:"Can I pay on the website now?", qt:"இப்போது இணையதளத்தில் பணம் செலுத்தலாமா?", a:"No. The current site accepts structured enquiries only while FSSAI registration, final recipes and the settlement account are pending. Pay only after San Bakes confirms a complete order summary and shares approved instructions.", at:"இல்லை. FSSAI பதிவு, இறுதி ரெசிபிகள் மற்றும் கட்டண கணக்கு நிலுவையில் உள்ளதால் தற்போது விசாரணைகள் மட்டுமே ஏற்கப்படுகின்றன." },
];

export default function FAQPage() {
  const { language } = useLanguage(); const en = language === "en";
  return <main><section className="innerHero faqHero"><p className="eyebrow">QUESTIONS, ANSWERED CLEARLY</p><h1>{en ? "Everything to know before you reserve." : "முன்பதிவு செய்வதற்கு முன் தெரிந்துகொள்ள வேண்டியவை."}</h1><p>{en ? "Ingredients, formulations, timing, delivery, storage, changes and payment—without vague promises." : "பொருட்கள், வகைகள், நேரம், டெலிவரி, சேமிப்பு, மாற்றங்கள் மற்றும் கட்டணம்—தெளிவான பதில்களுடன்."}</p></section><section className="faqSection"><div className="faqIntro"><p className="eyebrow dark">SAN BAKES FAQ</p><h2>{en ? "Straight answers build trust." : "நேரான பதில்களே நம்பிக்கையை உருவாக்கும்."}</h2><p>{en ? "Final product labels and your confirmed order summary take priority if they contain more specific information." : "குறிப்பிட்ட தகவல் இருந்தால் இறுதி தயாரிப்பு லேபிளும் உறுதி செய்யப்பட்ட ஆர்டர் சுருக்கமும் முன்னுரிமை பெறும்."}</p></div><div className="faqList">{questions.map((item,index) => <details key={item.q} open={index===0}><summary><span>{String(index+1).padStart(2,"0")}</span><strong>{en ? item.q : item.qt}</strong><i>+</i></summary><p>{en ? item.a : item.at}</p></details>)}</div><div className="faqCta"><div><strong>{en ? "Still deciding?" : "இன்னும் முடிவு செய்யவில்லையா?"}</strong><span>{en ? "Send the product, date and dietary concern on WhatsApp." : "தயாரிப்பு, தேதி மற்றும் உணவு தொடர்பான கேள்வியை WhatsApp-ல் அனுப்புங்கள்."}</span></div><a className="button buttonCacao" href="https://wa.me/919940058623?text=Hello%20San%20Bakes%2C%20I%20have%20a%20question%20before%20placing%20a%20preorder." target="_blank" rel="noreferrer">{en ? "Ask on WhatsApp" : "WhatsApp-ல் கேட்க"}</a></div><p className="faqPolicyLink"><a href="/policies">{en ? "Read the complete proposed order, cancellation and allergen policies →" : "முழு ஆர்டர், ரத்து மற்றும் அலர்ஜன் கொள்கைகளைப் படிக்க →"}</a></p></section></main>;
}
